--TỔNG SỐ TABLE: 18

USE master
GO
CREATE DATABASE QL_TRUNGTAMANHNGU
GO
USE QL_TRUNGTAMANHNGU


---------------------------------------------------CREATE TABLE
GO
CREATE TABLE PHANQUYEN
(
	NHOM NVARCHAR(20) NOT NULL PRIMARY KEY,
	QUYEN VARCHAR(30)
)

CREATE TABLE TAIKHOAN
(
	TENTK VARCHAR(20) NOT NULL PRIMARY KEY,
	MATKHAU VARCHAR(50),
	NHOM NVARCHAR(20),
)

CREATE TABLE LICH
(
	THU INT NOT NULL,
	BUOI INT NOT NULL,
	TIET VARCHAR(10) NOT NULL,
	CONSTRAINT PK_LICH PRIMARY KEY(THU, BUOI, TIET)
)

CREATE TABLE DIACHI
(
	TINH_THANHPHO NVARCHAR(100) NOT NULL,
	QUAN_HUYEN NVARCHAR(100) NOT NULL,
	PHUONG_XA NVARCHAR(100) NOT NULL,
	DUONG NVARCHAR(100) NOT NULL,
	CONSTRAINT PK_DIACHI PRIMARY KEY(TINH_THANHPHO, QUAN_HUYEN, PHUONG_XA, DUONG)
)

CREATE TABLE CHUCVU
(
	MACV INT IDENTITY(1,1) PRIMARY KEY,
	TENCV NVARCHAR(50)
)

CREATE TABLE NHANVIEN
(
	MSNV INT IDENTITY(1,1) PRIMARY KEY,
	TENNV NVARCHAR(50),
	LUONGCUNG FLOAT,
	HSL FLOAT,
	TRINHDO INT,
	HINHANH NVARCHAR(100),
	NGAYSINH DATE,
	KINHNGHIEM INT,
	TINH_THANHPHO NVARCHAR(100),
	QUAN_HUYEN NVARCHAR(100),
	PHUONG_XA NVARCHAR(100),
	DUONG NVARCHAR(100),
	CHUCVU INT,
	TENTK VARCHAR(20)
)

CREATE TABLE CTNHANVIEN
(
	MSNV INT NOT NULL,
	MALOP INT NOT NULL,
	CONSTRAINT PK_CTNV PRIMARY KEY(MSNV, MALOP)
)

CREATE TABLE LOAILOP
(
	MALOAILOP INT IDENTITY(1,1) PRIMARY KEY,
	TENLOP NVARCHAR(100),
	LOTRINH FLOAT,
	HOCPHI FLOAT
)

CREATE TABLE PHONG
(
	MAPHONG VARCHAR(30) NOT NULL PRIMARY KEY,
	SOCHONGOI INT
)

CREATE TABLE CTPHONG
(
	MAPHONG VARCHAR(30) NOT NULL,
	THU INT NOT NULL,
	BUOI INT NOT NULL,
	TIET VARCHAR(10) NOT NULL,
	CONSTRAINT PK_CTPHONG PRIMARY KEY(MAPHONG, THU, BUOI, TIET)
)

CREATE TABLE LOPHOC
(
	MALOP INT IDENTITY(1,1) PRIMARY KEY,
	MALOAILOP INT,
	THU INT NOT NULL,
	BUOI INT NOT NULL,
	TIET VARCHAR(10) NOT NULL,
	SOLUONGDANGKY_TOIDA INT DEFAULT 0,
	SOLUONGDADANGKY INT DEFAULT 0
)

CREATE TABLE CTLOPHOC
(
	MALOP INT NOT NULL,
	MAPHONG VARCHAR(30) NOT NULL,
	CONSTRAINT PK_CTLOP PRIMARY KEY(MALOP, MAPHONG)
)

CREATE TABLE HOCVIEN
(
	MAHV INT IDENTITY(1,1) PRIMARY KEY,
	TENHV NVARCHAR(50),
	SDT VARCHAR(20),
	EMAIL VARCHAR(50),
	TINH_THANHPHO NVARCHAR(100),
	QUAN_HUYEN NVARCHAR(100),
	PHUONG_XA NVARCHAR(100),
	DUONG NVARCHAR(100),
	HINHANH NVARCHAR(100),
	NGAYSINH DATE,
)

CREATE TABLE CTHOCVIEN
(
	MAHV INT NOT NULL,
	MALOP INT NOT NULL,
	CONSTRAINT PK_CTHOCVIEN PRIMARY KEY(MAHV, MALOP)
)

CREATE TABLE HOADON
(
	MAHD INT IDENTITY(1,1) PRIMARY KEY,
	MAHV INT NOT NULL,
	MSNV INT NOT NULL,
	TONGTIEN FLOAT DEFAULT 0
)

CREATE TABLE CTHOADON
(
	MAHD INT NOT NULL,
	MALOAILOP INT NOT NULL,
	CONSTRAINT PK_CTHOADON PRIMARY KEY(MAHD, MALOAILOP)
)

CREATE TABLE DIEM
(
	DIEMSO FLOAT NOT NULL,
	MAHV INT NOT NULL,
	MALOP INT NOT NULL,
	LANTHI INT NOT NULL
	CONSTRAINT PK_CTDIEM PRIMARY KEY(DIEMSO, MAHV, MALOP, LANTHI)
)

CREATE TABLE CHAMCONG
(
	MSNV INT NOT NULL,
	THU INT NOT NULL,
	BUOI INT NOT NULL,
	TIET VARCHAR(10) NOT NULL,
	CONSTRAINT PK_CHAMCONG PRIMARY KEY(MSNV, THU, BUOI, TIET)
)



--------------------------------------------------------ADD KHOA NGOAI

GO
ALTER TABLE TAIKHOAN
ADD CONSTRAINT FK_TAIKHOAN_NHOM FOREIGN KEY (NHOM) REFERENCES PHANQUYEN(NHOM)

GO
ALTER TABLE DIEM
ADD CONSTRAINT FK_CTDIEM_MAHV FOREIGN KEY (MAHV) REFERENCES HOCVIEN(MAHV)

GO
ALTER TABLE DIEM
ADD CONSTRAINT FK_CTDIEM_MALOP FOREIGN KEY (MALOP) REFERENCES LOPHOC(MALOP)

GO
ALTER TABLE NHANVIEN
ADD CONSTRAINT FK_NHANVIEN_CHUCVU FOREIGN KEY (CHUCVU) REFERENCES CHUCVU(MACV)

GO
ALTER TABLE NHANVIEN
ADD CONSTRAINT FK_NHANVIEN_DIACHI FOREIGN KEY (TINH_THANHPHO, QUAN_HUYEN, PHUONG_XA, DUONG) REFERENCES DIACHI(TINH_THANHPHO, QUAN_HUYEN, PHUONG_XA, DUONG)

GO
ALTER TABLE NHANVIEN
ADD CONSTRAINT FK_NHANVIEN_TENTK FOREIGN KEY (TENTK) REFERENCES TAIKHOAN(TENTK)

GO
ALTER TABLE LOPHOC
ADD CONSTRAINT FK_LOPHOC_MALOAILOP FOREIGN KEY (MALOAILOP) REFERENCES LOAILOP(MALOAILOP)

GO
ALTER TABLE LOPHOC
ADD CONSTRAINT FK_LOPHOC_LICH FOREIGN KEY (THU,BUOI,TIET) REFERENCES LICH(THU,BUOI,TIET)

GO
ALTER TABLE CTLOPHOC
ADD CONSTRAINT FK_CTLOPHOC_MALOP FOREIGN KEY (MALOP) REFERENCES LOPHOC(MALOP)

GO
ALTER TABLE CTLOPHOC
ADD CONSTRAINT FK_CTLOPHOC_MAPHONG FOREIGN KEY (MAPHONG) REFERENCES PHONG(MAPHONG)

GO
ALTER TABLE CTPHONG
ADD CONSTRAINT FK_CTPHONG_MAPHONG FOREIGN KEY (MAPHONG) REFERENCES PHONG(MAPHONG)

GO
ALTER TABLE CTPHONG
ADD CONSTRAINT FK_CTPHONG_LICH FOREIGN KEY (THU,BUOI,TIET) REFERENCES LICH(THU,BUOI,TIET)

GO
ALTER TABLE CTHOCVIEN
ADD CONSTRAINT FK_CTHOCVIEN_MAHV FOREIGN KEY (MAHV) REFERENCES HOCVIEN(MAHV)

GO
ALTER TABLE CTHOCVIEN
ADD CONSTRAINT FK_CTHOCVIEN_MALOP FOREIGN KEY (MALOP) REFERENCES LOPHOC(MALOP)

GO
ALTER TABLE CTNHANVIEN
ADD CONSTRAINT FK_CTNHANVIEN_MSNV FOREIGN KEY (MSNV) REFERENCES NHANVIEN(MSNV)

GO
ALTER TABLE CTNHANVIEN
ADD CONSTRAINT FK_CTNHANVIEN_MALOP FOREIGN KEY (MALOP) REFERENCES LOPHOC(MALOP)

GO
ALTER TABLE HOADON
ADD CONSTRAINT FK_HOADON_MAHV FOREIGN KEY (MAHV) REFERENCES HOCVIEN(MAHV)

GO
ALTER TABLE HOADON
ADD CONSTRAINT FK_HOADON_MSNV FOREIGN KEY (MSNV) REFERENCES NHANVIEN(MSNV)

GO
ALTER TABLE CTHOADON
ADD CONSTRAINT FK_CTHOADON_MAHD FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD)

GO
ALTER TABLE CTHOADON
ADD CONSTRAINT FK_CTHOADON_MALOAILOP FOREIGN KEY (MALOAILOP) REFERENCES LOAILOP(MALOAILOP)

GO
ALTER TABLE CHAMCONG
ADD CONSTRAINT FK_CHAMCONG_MSNV FOREIGN KEY (MSNV) REFERENCES NHANVIEN(MSNV)

GO
ALTER TABLE CHAMCONG
ADD CONSTRAINT FK_CHAMCONG_LICH FOREIGN KEY (THU,BUOI,TIET) REFERENCES LICH(THU,BUOI,TIET)

GO
ALTER TABLE HOCVIEN
ADD CONSTRAINT FK_HOCVIEN_DIACHI FOREIGN KEY (TINH_THANHPHO, QUAN_HUYEN, PHUONG_XA, DUONG) REFERENCES DIACHI(TINH_THANHPHO, QUAN_HUYEN, PHUONG_XA, DUONG)





------------------------------------------------INSERT

--Phan Quyen
GO
INSERT INTO PHANQUYEN 
VALUES ('Nhan Vien', 'SELECT, INSERT, DELETE, UPDATE'),
	('admin', 'ALL')

--Tai khoan
GO
INSERT INTO TAIKHOAN
VALUES ('hoangnhan123', '123', 'Nhan Vien'), ('leluuhoangnhan', '123', 'admin')

--Lich
GO
INSERT INTO LICH
VALUES (2, 1, '1 -> 5'),
	(2, 2, '7 -> 11'),
	(3, 1, '1 -> 5'),
	(3, 2, '7 -> 11'),
	(4, 1, '1 -> 5'),
	(4, 2, '7 -> 11'),
	(5, 1, '1 -> 5'),
	(5, 2, '7 -> 11'),
	(6, 1, '1 -> 5'),
	(6, 2, '7 -> 11'),
	(7, 1, '1 -> 5'),
	(7, 2, '7 -> 11')

--Dia chi
GO
INSERT INTO DIACHI
VALUES (N'Hồ Chí Minh',N'Quận 12',N'Phường An Phú Đông', N'Đường 1'),
	(N'Hồ Chí Minh',N'Quận 12',N'Phường Hiệp Thành', N'Đường 5'),
	(N'Hồ Chí Minh',N'Huyện Hóc Môn',N'Xã Thới Tam Thôn', N'Trịnh Thị Miếng'),
	(N'Hồ Chí Minh',N'Huyện Hóc Môn',N'Tân Sơn Nhì', N'Đường 13'),
	(N'Hà Nội',N'Quận Mê Linh',N'Xã Chu Phan', N'Đường 10'),
	(N'Hà Nội',N'Quận Hoàn Kiếm',N'Phường Hàn Mã', N'Đường 15')

--Chuc vu
GO
INSERT INTO CHUCVU(TENCV)
VALUES (N'Giảng Viên'), (N'Lao Công'), (N'Ban Giám Hiệu')

--Nhan vien
GO
SET DATEFORMAT DMY
INSERT INTO NHANVIEN (TENNV,TRINHDO,NGAYSINH,KINHNGHIEM,TINH_THANHPHO,QUAN_HUYEN,PHUONG_XA,DUONG,CHUCVU,TENTK)
VALUES (N'Lê Lưu Hoàng Nhân', 4, '01/03/2001',2,N'Hồ Chí Minh',N'Huyện Hóc Môn',N'Xã Thới Tam Thôn', N'Trịnh Thị Miếng',3,'leluuhoangnhan'),
	(N'Hoàng Nhân', 3, '25/08/2002',2,N'Hà Nội',N'Quận Hoàn Kiếm',N'Phường Hàn Mã', N'Đường 15',1,'hoangnhan123')

--Loai lop
GO
INSERT INTO LOAILOP (TENLOP, LOTRINH, HOCPHI)
VALUES (N'TOEIC',3.5,2000000), (N'TOEFL',2.5,4000000), (N'IELTS',2,5500000), (N'FCE',1.5,10000000)

--Lop
GO
INSERT INTO LOPHOC (MALOAILOP, THU, BUOI, TIET, SOLUONGDANGKY_TOIDA)
VALUES (1, 7, 2, '7 -> 11', 300), (2, 3, 1, '1 -> 5', 200), (3, 4, 2, '7 -> 11', 350), (4, 2, 1, '1 -> 5', 250), (1, 2, 1, '1 -> 5', 100)

--Phong
GO
INSERT INTO PHONG
VALUES ('A301',100), ('B501',150), ('F202',350)

--Chi tiet lop
GO
INSERT INTO CTLOPHOC
VALUES (1,'A301'), (2,'B501'), (3,'F202'), (4,'B501')

--Chi tiet nhan vien
GO
INSERT INTO CTNHANVIEN
VALUES (2,3),(2,1)

--Hoc vien
GO
SET DATEFORMAT DMY
INSERT INTO HOCVIEN (TENHV, SDT, EMAIL,TINH_THANHPHO, QUAN_HUYEN, PHUONG_XA,DUONG,NGAYSINH)
VALUES (N'Nguyễn Văn A', '0938237485', 'leluuhoangnhan@gmail.com',N'Hồ Chí Minh',N'Huyện Hóc Môn',N'Xã Thới Tam Thôn', N'Trịnh Thị Miếng','01/03/2001'),
	(N'Nguyễn Văn B', '0123456789', 'moi1@gmail.com',N'Hà Nội',N'Quận Hoàn Kiếm',N'Phường Hàn Mã', N'Đường 15','25/08/1999'),
	(N'Nguyễn Văn C', '013572468', 'moi2@gmail.com',N'Hồ Chí Minh',N'Quận 12',N'Phường An Phú Đông', N'Đường 1','17/06/2003')


