/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.StringTokenizer;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LeLuuHoangNhan
 */
public class DuAn extends javax.swing.JFrame {
    private Connection conn;
    Vector nd=new Vector();
    Vector td=new Vector();
    
    public DuAn() {
        initComponents();
        this.setVisible(false);
        td.add("Ma Du An");
        td.add("Ten Du An");
        td.add("Dia Chi");
        td.add("Nam Ban Giao");
        td.add("Ma Khu Dat");
        td.add("So Luong KH");
        td.add("So Luong CDT");
        table_kq.setModel(new DefaultTableModel(nd,td));
        
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            conn=DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databasename=DB_QLDA;"
                    + "username=sa;password=1321");
            docdata();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        
        txt_soLuongCDT.setEnabled(false);
        txt_soLuongKH.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_maduan = new javax.swing.JTextField();
        txt_tenduan = new javax.swing.JTextField();
        txt_diachi = new javax.swing.JTextField();
        txt_nambangiao = new javax.swing.JTextField();
        txt_makhudat = new javax.swing.JTextField();
        but_them = new javax.swing.JButton();
        but_capnhat = new javax.swing.JButton();
        but_xoa = new javax.swing.JButton();
        but_timkiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_kq = new javax.swing.JTable();
        but_xuatfile = new javax.swing.JButton();
        but_nhapfile = new javax.swing.JButton();
        but_dong = new javax.swing.JButton();
        btn_lamMoi = new javax.swing.JButton();
        btn_removeAll = new javax.swing.JButton();
        btn_saoLuu = new javax.swing.JButton();
        btn_khoiPhuc = new javax.swing.JButton();
        Quaylai = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_soLuongKH = new javax.swing.JTextField();
        txt_soLuongCDT = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Dự Án");

        jLabel2.setText("Mã Dự Án");

        jLabel3.setText("Tên Dự Án");

        jLabel4.setText("Địa Chỉ");

        jLabel5.setText("Năm Bàn Giao");

        jLabel6.setText("Mã Khu Đất");

        txt_makhudat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_makhudatActionPerformed(evt);
            }
        });

        but_them.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        but_them.setText("Thêm mới");
        but_them.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        but_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_themActionPerformed(evt);
            }
        });

        but_capnhat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        but_capnhat.setText("Cập nhật");
        but_capnhat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        but_capnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_capnhatActionPerformed(evt);
            }
        });

        but_xoa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        but_xoa.setText("Xóa");
        but_xoa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        but_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_xoaActionPerformed(evt);
            }
        });

        but_timkiem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        but_timkiem.setText("Tìm kiếm");
        but_timkiem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        but_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_timkiemActionPerformed(evt);
            }
        });

        table_kq.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        table_kq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                table_kqMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(table_kq);

        but_xuatfile.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        but_xuatfile.setText("Xuất file.txt");
        but_xuatfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_xuatfileActionPerformed(evt);
            }
        });

        but_nhapfile.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        but_nhapfile.setText("Nhập file.txt");
        but_nhapfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_nhapfileActionPerformed(evt);
            }
        });

        but_dong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        but_dong.setText("Đóng");
        but_dong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                but_dongMouseClicked(evt);
            }
        });

        btn_lamMoi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_lamMoi.setText("Làm Mới");
        btn_lamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lamMoiActionPerformed(evt);
            }
        });

        btn_removeAll.setBackground(new java.awt.Color(255, 0, 0));
        btn_removeAll.setText("Remove All");
        btn_removeAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removeAllActionPerformed(evt);
            }
        });

        btn_saoLuu.setBackground(new java.awt.Color(255, 204, 102));
        btn_saoLuu.setText("Sao lưu");
        btn_saoLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saoLuuActionPerformed(evt);
            }
        });

        btn_khoiPhuc.setBackground(new java.awt.Color(204, 255, 102));
        btn_khoiPhuc.setText("Khôi phục");
        btn_khoiPhuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_khoiPhucActionPerformed(evt);
            }
        });

        Quaylai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Quaylai.setText("Quay lại");
        Quaylai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuaylaiActionPerformed(evt);
            }
        });

        jLabel7.setText("Số lượng KH");

        jLabel8.setText("Số lượng CDT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(259, 259, 259))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_maduan, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_soLuongCDT, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_tenduan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addComponent(txt_diachi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addComponent(txt_nambangiao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addComponent(txt_makhudat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addComponent(txt_soLuongKH, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(but_capnhat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(but_them, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                    .addComponent(but_xoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(but_timkiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(but_xuatfile)
                        .addGap(18, 18, 18)
                        .addComponent(but_nhapfile)
                        .addGap(40, 40, 40)
                        .addComponent(btn_lamMoi)
                        .addGap(31, 31, 31)
                        .addComponent(Quaylai)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_khoiPhuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_saoLuu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(but_dong, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(btn_removeAll)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_makhudat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_maduan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(40, 40, 40))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_tenduan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(but_them)
                                .addComponent(jLabel3)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txt_diachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(but_capnhat)
                                .addGap(5, 5, 5)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_nambangiao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(but_xoa)
                        .addGap(12, 12, 12)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(but_timkiem)
                            .addComponent(txt_soLuongKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(77, 77, 77)
                        .addComponent(btn_saoLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_khoiPhuc, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_soLuongCDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btn_removeAll)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(but_dong)
                    .addComponent(Quaylai)
                    .addComponent(btn_lamMoi)
                    .addComponent(but_nhapfile)
                    .addComponent(but_xuatfile))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void docdata()
    {
        String sql="SELECT * FROM DUAN";
        try{
            PreparedStatement ps=conn.prepareStatement(sql);
            ResultSet rs=ps.executeQuery();
            while(rs.next())
            {
                String maDA=rs.getString(1);
                String tenDA=rs.getString(2);
                String diaChi=rs.getString(3);
                int namBG=rs.getInt(4);
                String maKD=rs.getString(5);
                int soLuongKH=rs.getInt(6);
                int soLuongCDT=rs.getInt(7);
                
                
                
                Vector r=new Vector();
                r.add(maDA);
                r.add(tenDA);
                r.add(diaChi);
                r.add(namBG);
                r.add(maKD);
                r.add(soLuongKH);
                r.add(soLuongCDT);
                
                nd.add(r);
                table_kq.setModel(new DefaultTableModel(nd,td));
            }
            rs.close();
            ps.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "Doc du lieu loi !");
            e.printStackTrace();
        }
        
    }
    
    private void txt_makhudatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_makhudatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_makhudatActionPerformed

    private void but_dongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_but_dongMouseClicked
        JFrame f=new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(f, "Bạn có muốn thoát chương trình ?", "Thông báo", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
            System.exit(0);
    }//GEN-LAST:event_but_dongMouseClicked

    private void but_xuatfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_xuatfileActionPerformed
        int k=1;
        try{
            File f=new File("E:/DUAN.TXT");
            while(f.exists())
            {
                f=new File("E:/DUAN" + "(" + k + ")" + ".TXT");
                k++;
            }
            FileWriter fw=new FileWriter(f);
            for(int i=0;i<table_kq.getRowCount();i++)
            {
                  fw.write((String) table_kq.getValueAt(i, 0)+";");
                  fw.write((String) table_kq.getValueAt(i, 1)+";");
                  fw.write((String) table_kq.getValueAt(i, 2)+";");
                  fw.write( String.valueOf(table_kq.getValueAt(i, 3))+";");
                  fw.write((String) table_kq.getValueAt(i, 4) + ";");
                  fw.write( String.valueOf(table_kq.getValueAt(i, 5))+";");
                  fw.write( String.valueOf(table_kq.getValueAt(i, 6))+";");
                  if(i+1!=table_kq.getRowCount())
                      fw.write("\n");
            }
            fw.close();
            JOptionPane.showMessageDialog(this, "Xuat file thanh cong !");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "Loi xuat file !");
            e.printStackTrace();
        }
    }//GEN-LAST:event_but_xuatfileActionPerformed

    private void but_nhapfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_nhapfileActionPerformed

            int nhapFile=this.nhapFileThemMoi("E:/DUAN.TXT");
            if(nhapFile!=0)
            {
                int nhap=this.nhapDataVaoSQL(nhapFile);
                if(nhap!=0)
                {
                    this.setVisible(false);
                    DuAn da=new DuAn();
                    da.setVisible(true);
                    JOptionPane.showMessageDialog(this,"Nhap file thanh cong !");
                }
                else{
                    JOptionPane.showMessageDialog(this,"Nhap file khong thanh cong !");
                }
            }
            else{
                JOptionPane.showMessageDialog(this,"Nhap file.txt vao java khong thanh cong !");
            }
    }//GEN-LAST:event_but_nhapfileActionPerformed

    
    private void but_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_timkiemActionPerformed

        String maDA=txt_maduan.getText().toString();
        if(maDA.equals(""))
        {
            JOptionPane.showMessageDialog(this,"Ma Du An =>>> Không được bỏ trống !");
        }
        else{
            int tk=timKiem(maDA);
            if(tk!=0)
            {
                JOptionPane.showMessageDialog(this,"Tìm thấy tại vị trí thứ : " + tk);
            }
            else{
                JOptionPane.showMessageDialog(this,"Không tìm thấy !");
            }
        }
    }//GEN-LAST:event_but_timkiemActionPerformed

    private void table_kqMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_kqMousePressed
        int row=table_kq.getSelectedRow();
        txt_maduan.setText((String) table_kq.getValueAt(row, 0));
        txt_tenduan.setText((String) table_kq.getValueAt(row, 1));
        txt_diachi.setText((String) table_kq.getValueAt(row, 2));
        txt_nambangiao.setText((String) String.valueOf(table_kq.getValueAt(row, 3)));
        txt_makhudat.setText((String) table_kq.getValueAt(row, 4));
        txt_soLuongKH.setText((String) String.valueOf(table_kq.getValueAt(row, 5)));
        txt_soLuongCDT.setText((String) String.valueOf(table_kq.getValueAt(row, 6)));
    }//GEN-LAST:event_table_kqMousePressed

    private void but_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_xoaActionPerformed

        String maDA=txt_maduan.getText().toString();        
        if(maDA.equals(""))
        {
            JOptionPane.showMessageDialog(this,"Ma Du An =>>> Không được bỏ trống !");
        }
        else
        {
            String sql="DELETE FROM DUAN WHERE MADUAN=?";
            try{
                PreparedStatement ps=conn.prepareStatement(sql);
                ps.setString(1,maDA);

                ps.executeUpdate();
                ps.close();
                this.setVisible(false);
                DuAn da=new DuAn();
                da.setVisible(true);
                JOptionPane.showMessageDialog(this,"Xóa dữ liệu thành công !");
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this,"Xóa dữ liệu không thành công !");
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_but_xoaActionPerformed

    private void but_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_themActionPerformed
        String maDA=txt_maduan.getText().toString();
        String tenDA=txt_tenduan.getText().toString();
        String diaChi=txt_diachi.getText().toString();
        String namBG=txt_nambangiao.getText().toString();
        String maKD=txt_makhudat.getText().toString();
        
        if(maDA.equals("")||tenDA.equals("")||diaChi.equals("")||namBG.equals("")||maKD.equals(""))
        {
            JOptionPane.showMessageDialog(this,"Không được bỏ trống các mục phía trên!");
        }
        else
        {
            String sql="INSERT INTO DUAN " + "VALUES(?,?,?,?,?,?,?)";
            try{
                PreparedStatement ps=conn.prepareStatement(sql);
                ps.setString(1,maDA);
                ps.setString(2,tenDA);
                ps.setString(3,diaChi);
                ps.setString(4,namBG);
                ps.setString(5,maKD);
                ps.setString(6,"0");
                ps.setString(7,"0");

                ps.executeUpdate();
                ps.close();
                this.setVisible(false);
                DuAn da=new DuAn();
                da.setVisible(true);
                JOptionPane.showMessageDialog(this,"Thêm mới thành công !");
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this,"Thêm mới không thành công !");
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_but_themActionPerformed

    private void but_capnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_capnhatActionPerformed
        int row=table_kq.getSelectedRow();
        String maDA=table_kq.getValueAt(row, 0).toString();
        String tenDA=table_kq.getValueAt(row, 1).toString();
        String diaChi=table_kq.getValueAt(row, 2).toString();
        String namBG=table_kq.getValueAt(row, 3).toString();
        String maKD=table_kq.getValueAt(row, 4).toString();
        
        String maDA1=txt_maduan.getText().toString();
        String tenDA1=txt_tenduan.getText().toString();
        String diaChi1=txt_diachi.getText().toString();
        String namBG1=String.valueOf(txt_nambangiao.getText());
        String maKD1=txt_makhudat.getText().toString();
        
        if(maDA1.equals("")||tenDA1.equals("")||diaChi1.equals("")||namBG1.equals("")||maKD1.equals(""))
        {
            JOptionPane.showMessageDialog(this,"Không được bỏ trống mục nào phía trên!");
        }
        else
        {
            String sql="UPDATE DUAN " + "SET MADUAN=?, TENDUAN=?, DIACHI=?, NAMBG=?, MAKD=? " 
                    +"WHERE MADUAN=? AND TENDUAN=? AND DIACHI=? AND NAMBG=? AND MAKD=?";

            try{
                PreparedStatement ps=conn.prepareStatement(sql);
                ps.setString(1,maDA1);
                ps.setString(2,tenDA1);
                ps.setString(3,diaChi1);
                ps.setString(4,namBG1);
                ps.setString(5,maKD1);

                ps.setString(6,maDA);
                ps.setString(7,tenDA);
                ps.setString(8,diaChi);
                ps.setString(9,namBG);
                ps.setString(10,maKD);

                ps.executeUpdate();
                ps.close();
                this.setVisible(false);
                DuAn da=new DuAn();
                da.setVisible(true);
                JOptionPane.showMessageDialog(this,"Cập nhật thành công !");
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this,"Cập nhật không thành công !");
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_but_capnhatActionPerformed

    private void btn_lamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lamMoiActionPerformed
        this.setVisible(false);
        DuAn da=new DuAn();
        da.setVisible(true);
    }//GEN-LAST:event_btn_lamMoiActionPerformed

    private void btn_saoLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saoLuuActionPerformed
        String sql="EXEC DBO.TT_BACKUP";
        try{
            PreparedStatement ps=conn.prepareStatement(sql);
            ps.execute();
            ps.close();
            
            JOptionPane.showMessageDialog(this, "Sao lưu dữ liệu thành công!");
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Sao lưu dữ liệu không thành công!");
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btn_saoLuuActionPerformed

    private void btn_khoiPhucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_khoiPhucActionPerformed
        String sql="USE master " + "EXEC DBO.TT_RESTORE";
        try{
            PreparedStatement ps=conn.prepareStatement(sql);
            ps.executeUpdate();
            ps.close();
            this.conn.close();
            
            
            this.setVisible(false);
            DuAn da=new DuAn();
            da.setVisible(true);
            JOptionPane.showMessageDialog(this, "Khôi phục dữ liệu thành công!");
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Khôi phục dữ liệu không thành công!");
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btn_khoiPhucActionPerformed

    private void btn_removeAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeAllActionPerformed
        String sql="DELETE FROM DUAN";
        try
        {
            PreparedStatement ps=conn.prepareStatement(sql);
            ps.executeUpdate();
            ps.close();
            
            this.setVisible(false);
            DuAn da=new DuAn();
            da.setVisible(true);
            JOptionPane.showMessageDialog(this, "Remove All thành công!");
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Remove All không thành công!");
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btn_removeAllActionPerformed

    private void QuaylaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuaylaiActionPerformed
        // TODO add your handling code here:
                            this.setVisible(false);
            ChonLua da=new ChonLua();
            da.setVisible(true);
    }//GEN-LAST:event_QuaylaiActionPerformed

    public int timKiem(String maDA)
    {
        int kt=1;
        String sql1="SELECT * FROM DUAN";
        try{
            PreparedStatement ps1=conn.prepareStatement(sql1);
            ResultSet rs=ps1.executeQuery();
            while(rs.next())
            {
                if(maDA.equals(rs.getString("MADUAN")))
                {
                   return kt; 
                }
                kt++;
            }
            rs.close();
            ps1.close();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        return 0;
    }
    
    public int nhapFileThemMoi(String url)
    {
        int kq=0;
        try{
            File f = new File(url);
            if (f.exists())
            {
                try(BufferedReader br=new BufferedReader(new FileReader(f)))
                {
                    String value;
                    while((value=br.readLine())!=null)
                    {
                        StringTokenizer stk=new StringTokenizer(value,";");
                        String maDA=stk.nextToken();
                        String tenDA=stk.nextToken();
                        String diaChi=stk.nextToken();
                        String namBG=String.valueOf(stk.nextToken());
                        String maKD=stk.nextToken();
                        String soLuongKH=String.valueOf(stk.nextToken());
                        String soLuongCDT=String.valueOf(stk.nextToken());
                        Vector r=new Vector();
                        r.add(maDA);
                        r.add(tenDA);
                        r.add(diaChi);
                        r.add(namBG);
                        r.add(maKD);
                        r.add(soLuongKH);
                        r.add(soLuongCDT);
                        nd.add(r);
                        kq++;
                    }
                }
            }
            
            return kq;
        }
        catch(Exception e){
            e.printStackTrace();
            return kq;
        }
    }
    
    public int nhapDataVaoSQL(int x)
    {
        int kq=0;
        int kt;
        if(x!=0)
        {
            for(int i=0;i<table_kq.getRowCount();i++)
            {
                String maDA = (String) table_kq.getValueAt(i, 0);
                String tenDA = (String) table_kq.getValueAt(i, 1);
                String diaChi = (String) table_kq.getValueAt(i, 2);
                String namBG = String.valueOf(table_kq.getValueAt(i, 3));
                String maKD = (String) table_kq.getValueAt(i, 4);
                String soLuongKH = String.valueOf(table_kq.getValueAt(i, 5));
                String soLuongCDT = String.valueOf(table_kq.getValueAt(i, 6));
                kt=kiemTraMDAExists(maDA);
                if(kt==0)
                {
                    String sql="INSERT INTO DUAN VALUES(?,?,?,?,?,?,?)";
                    try{
                        PreparedStatement ps=conn.prepareStatement(sql);
                        ps.setString(1, maDA);
                        ps.setString(2, tenDA);
                        ps.setString(3,diaChi);
                        ps.setString(4, namBG);
                        ps.setString(5, maKD);
                        ps.setString(6, soLuongKH);
                        ps.setString(7, soLuongCDT);

                        ps.executeUpdate();
                        ps.close();
                        kq++;
                    }
                    catch(Exception e)
                    {
                        e.printStackTrace(); 
                    }
                }
                
                
            }
        }
        else{
            JOptionPane.showMessageDialog(this,"Không có dữ liệu mới !");
        }
                
        return kq;
    }
    

    
    public int kiemTraMDAExists(String maDA)
    {
        int kt=0;
        String sql1="SELECT * FROM DUAN";
        try{
            PreparedStatement ps1=conn.prepareStatement(sql1);
            ResultSet rs=ps1.executeQuery();
            while(rs.next())
            {
                if(maDA.equals(rs.getString("MADUAN")))
                {
                    kt++;
                }
            }
            rs.close();
            ps1.close();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        return kt;
    }
    

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DuAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DuAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DuAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DuAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DuAn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Quaylai;
    private javax.swing.JButton btn_khoiPhuc;
    private javax.swing.JButton btn_lamMoi;
    private javax.swing.JButton btn_removeAll;
    private javax.swing.JButton btn_saoLuu;
    private javax.swing.JButton but_capnhat;
    private javax.swing.JButton but_dong;
    private javax.swing.JButton but_nhapfile;
    private javax.swing.JButton but_them;
    private javax.swing.JButton but_timkiem;
    private javax.swing.JButton but_xoa;
    private javax.swing.JButton but_xuatfile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_kq;
    private javax.swing.JTextField txt_diachi;
    private javax.swing.JTextField txt_maduan;
    private javax.swing.JTextField txt_makhudat;
    private javax.swing.JTextField txt_nambangiao;
    private javax.swing.JTextField txt_soLuongCDT;
    private javax.swing.JTextField txt_soLuongKH;
    private javax.swing.JTextField txt_tenduan;
    // End of variables declaration//GEN-END:variables
}
