/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.StringTokenizer;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LeLuuHoangNhan
 */
public class KhuDat extends javax.swing.JFrame {
    private Connection conn;
    
    Vector td=new Vector();
    Vector nd=new Vector();
     
    public KhuDat() {
        initComponents();
        this.setVisible(false);
        td.add("MaKD");
        td.add("Chu So Huu");
        td.add("Ma Du An");
        table_kq.setModel(new DefaultTableModel(nd,td));
        
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            conn=DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databasename=DB_QLDA;"
                    + "username=sa;password=1321");
            docdata();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        but_nhapfile1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_makd = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_chusohuu = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_maduan = new javax.swing.JTextField();
        but_capnhat = new javax.swing.JButton();
        but_them = new javax.swing.JButton();
        but_xoa = new javax.swing.JButton();
        but_timkiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_kq = new javax.swing.JTable();
        but_xuatfile = new javax.swing.JButton();
        but_nhapfile = new javax.swing.JButton();
        but_dong = new javax.swing.JButton();
        btn_lamMoi = new javax.swing.JButton();
        btn_removeAll = new javax.swing.JButton();
        btn_saoLuu = new javax.swing.JButton();
        btn_khoiPhuc = new javax.swing.JButton();
        Quaylai = new javax.swing.JButton();

        but_nhapfile1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        but_nhapfile1.setText("Nhập file.txt");
        but_nhapfile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_nhapfile1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Khu Đất");

        jLabel2.setText("Mã KĐ :");

        jLabel3.setText("Chủ sở hữu :");

        jLabel4.setText("Mã dự án :");

        but_capnhat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        but_capnhat.setText("Cập nhật");
        but_capnhat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        but_capnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_capnhatActionPerformed(evt);
            }
        });

        but_them.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        but_them.setText("Thêm Mới");
        but_them.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        but_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_themActionPerformed(evt);
            }
        });

        but_xoa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        but_xoa.setText("Xóa");
        but_xoa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        but_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_xoaActionPerformed(evt);
            }
        });

        but_timkiem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        but_timkiem.setText("Tìm kiếm");
        but_timkiem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        but_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_timkiemActionPerformed(evt);
            }
        });

        table_kq.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        table_kq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                table_kqMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(table_kq);

        but_xuatfile.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        but_xuatfile.setText("Xuất file.txt");
        but_xuatfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_xuatfileActionPerformed(evt);
            }
        });

        but_nhapfile.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        but_nhapfile.setText("Nhập file.txt");
        but_nhapfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_nhapfileActionPerformed(evt);
            }
        });

        but_dong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        but_dong.setText("Đóng");
        but_dong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                but_dongMouseClicked(evt);
            }
        });
        but_dong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_dongActionPerformed(evt);
            }
        });

        btn_lamMoi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_lamMoi.setText("Làm Mới");
        btn_lamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lamMoiActionPerformed(evt);
            }
        });

        btn_removeAll.setBackground(new java.awt.Color(255, 0, 0));
        btn_removeAll.setText("Remove All");
        btn_removeAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removeAllActionPerformed(evt);
            }
        });

        btn_saoLuu.setBackground(new java.awt.Color(255, 204, 102));
        btn_saoLuu.setText("Sao lưu");
        btn_saoLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saoLuuActionPerformed(evt);
            }
        });

        btn_khoiPhuc.setBackground(new java.awt.Color(204, 255, 102));
        btn_khoiPhuc.setText("Khôi phục");
        btn_khoiPhuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_khoiPhucActionPerformed(evt);
            }
        });

        Quaylai.setText("Quay lại");
        Quaylai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuaylaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_chusohuu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(txt_makd, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_maduan))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(but_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(but_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(but_them, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(but_capnhat, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_lamMoi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Quaylai)
                        .addGap(92, 92, 92)))
                .addGap(36, 36, 36))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(but_dong)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(but_xuatfile)
                        .addGap(28, 28, 28)
                        .addComponent(but_nhapfile))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btn_removeAll)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_khoiPhuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_saoLuu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(261, 261, 261))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_makd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_chusohuu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_maduan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(but_capnhat)
                            .addComponent(but_them))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(but_xoa)
                            .addComponent(but_timkiem))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(btn_saoLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(btn_khoiPhuc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_removeAll, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(but_xuatfile)
                    .addComponent(but_nhapfile))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(but_dong)
                    .addComponent(btn_lamMoi)
                    .addComponent(Quaylai))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void docdata()
    {
        String sql="SELECT * FROM KHUDAT";
        try{
            PreparedStatement ps=conn.prepareStatement(sql);
            ResultSet rs=ps.executeQuery();
            while(rs.next())
            {
                String maKD=rs.getString(1);
                String chuSH=rs.getString(2);
                String maDA=rs.getString(3);
                
                
                Vector r=new Vector();
                r.add(maKD);
                r.add(chuSH);
                r.add(maDA);
                
                nd.add(r);
                table_kq.setModel(new DefaultTableModel(nd,td));
            }
            rs.close();
            ps.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "Doc du lieu loi !");
            e.printStackTrace();
        }
        
    }
    
    private void but_dongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_but_dongMouseClicked
        JFrame f=new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(f, "Bạn có muốn thoát chương trình ?", "Thông báo", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
            System.exit(0);
    }//GEN-LAST:event_but_dongMouseClicked

    private void but_xuatfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_xuatfileActionPerformed
        int k=1;
        try{
            File f=new File("E:/KHUDAT.TXT");
            while(f.exists())
            {
                f=new File("E:/KHUDAT" + "(" + k + ")" + ".TXT");
                k++;
            }
            FileWriter fw=new FileWriter(f);
            for(int i=0;i<table_kq.getRowCount();i++)
            {
                  fw.write((String) table_kq.getValueAt(i, 0)+";");
                  fw.write((String) table_kq.getValueAt(i, 1)+";");
                  fw.write((String) table_kq.getValueAt(i, 2));
                  if(i+1!=table_kq.getRowCount())
                      fw.write("\n");
            }
            fw.close();
            JOptionPane.showMessageDialog(this, "Xuat file thanh cong !");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "Loi xuat file !");
            e.printStackTrace();
        }
    }//GEN-LAST:event_but_xuatfileActionPerformed

    private void but_nhapfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_nhapfileActionPerformed

        int nhapFile=this.nhapFileThemMoi("E:/KHUDAT.TXT");
        if(nhapFile!=0)
        {
            int nhap=this.nhapDataVaoSQL(nhapFile);
            if(nhap!=0)
            {
                this.setVisible(false);
                KhuDat kd=new KhuDat();
                kd.setVisible(true);
                JOptionPane.showMessageDialog(this,"Nhap file thanh cong !");
            }
            else{
                JOptionPane.showMessageDialog(this,"Nhap file khong thanh cong !");
            }
        }
        else{
            JOptionPane.showMessageDialog(this,"Nhap file.txt vao java khong thanh cong !");
        }
    }//GEN-LAST:event_but_nhapfileActionPerformed

    private void table_kqMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_kqMousePressed
        int row=table_kq.getSelectedRow();
        txt_makd.setText((String) table_kq.getValueAt(row, 0));
        txt_chusohuu.setText((String) table_kq.getValueAt(row, 1));
        txt_maduan.setText((String) table_kq.getValueAt(row, 2));
    }//GEN-LAST:event_table_kqMousePressed

    private void but_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_timkiemActionPerformed
        String maKD=txt_makd.getText().toString();
        if(maKD.equals(""))
        {
            JOptionPane.showMessageDialog(this,"Ma Khu Dat =>>> Không được bỏ trống !");
        }
        else{
            int tk=timKiem(maKD);
            if(tk!=0)
            {
                JOptionPane.showMessageDialog(this,"Tìm thấy tại vị trí thứ : " + tk);
            }
            else{
                JOptionPane.showMessageDialog(this,"Không tìm thấy !");
            }
        }
    }//GEN-LAST:event_but_timkiemActionPerformed

    private void but_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_xoaActionPerformed

        String maKD=txt_makd.getText().toString();
        if(maKD.equals(""))
        {
            JOptionPane.showMessageDialog(this,"Không được bỏ trống MaKD!");
        }
        else
        {
            String sql="DELETE FROM KHUDAT WHERE MAKD=?";
            try{
                PreparedStatement ps=conn.prepareStatement(sql);
                ps.setString(1,maKD);

                ps.executeUpdate();
                ps.close();
                this.setVisible(false);
                KhuDat kd=new KhuDat();
                kd.setVisible(true);
                JOptionPane.showMessageDialog(this,"Xóa dữ liệu thành công !");
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this,"Xóa dữ liệu không thành công !");
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_but_xoaActionPerformed

    private void but_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_themActionPerformed
        String maKD=txt_makd.getText().toString();
        String chuSH=txt_chusohuu.getText().toString();
        String maDA=txt_maduan.getText().toString();
        
        if(maKD.equals("")||chuSH.equals("")||maDA.equals(""))
        {
            JOptionPane.showMessageDialog(this,"Không được bỏ trống MAKD, CHUSH, MADA!");
        }
        else
        {
            String sql="INSERT INTO KHUDAT " + "VALUES(?,?,?)";
            try{
                PreparedStatement ps=conn.prepareStatement(sql);
                ps.setString(1,maKD);
                ps.setString(2,chuSH);
                ps.setString(3,maDA);

                ps.executeUpdate();
                ps.close();
                this.setVisible(false);
                KhuDat kd=new KhuDat();
                kd.setVisible(true);
                JOptionPane.showMessageDialog(this,"Thêm mới thành công !");
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this,"Thêm mới không thành công !");
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_but_themActionPerformed

    private void but_capnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_capnhatActionPerformed
        int row=table_kq.getSelectedRow();
        String maKD=table_kq.getValueAt(row, 0).toString();
        String chuSH=table_kq.getValueAt(row, 1).toString();
        String maDA=table_kq.getValueAt(row, 2).toString();
        
        String maKD1=txt_makd.getText().toString();
        String chuSH1=txt_chusohuu.getText().toString();
        String maDA1=txt_maduan.getText().toString();
        
        if(maKD1.equals("")||chuSH1.equals("")||maDA1.equals(""))
        {
            JOptionPane.showMessageDialog(this,"Không được bỏ trống MAKD, CHUSH, MADA!");
        }
        else
        {
            String sql="UPDATE KHUDAT " + "SET MAKD=?, CHUSOHUU=?, MADUAN=? " 
                    +"WHERE MAKD=? AND CHUSOHUU=? AND MADUAN=?";

            try{
                PreparedStatement ps=conn.prepareStatement(sql);
                ps.setString(1,maKD1);
                ps.setString(2,chuSH1);
                ps.setString(3,maDA1);

                ps.setString(4,maKD);
                ps.setString(5,chuSH);
                ps.setString(6,maDA);

                ps.executeUpdate();
                ps.close();
                this.setVisible(false);
                KhuDat kd=new KhuDat();
                kd.setVisible(true);
                JOptionPane.showMessageDialog(this,"Cập nhật thành công !");
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this,"Cập nhật không thành công !");
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_but_capnhatActionPerformed

    private void but_nhapfile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_nhapfile1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_but_nhapfile1ActionPerformed

    private void btn_lamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lamMoiActionPerformed
        this.setVisible(false);
        KhuDat kd=new KhuDat();
        kd.setVisible(true);
    }//GEN-LAST:event_btn_lamMoiActionPerformed

    private void but_dongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_dongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_but_dongActionPerformed

    private void btn_removeAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeAllActionPerformed
        String sql="DELETE FROM KHUDAT";
        try
        {
            PreparedStatement ps=conn.prepareStatement(sql);
            ps.executeUpdate();
            ps.close();
            
            this.setVisible(false);
            KhuDat kd=new KhuDat();
            kd.setVisible(true);
            JOptionPane.showMessageDialog(this, "Remove All thành công!");
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Remove All không thành công!");
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btn_removeAllActionPerformed

    private void btn_saoLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saoLuuActionPerformed
        String sql="EXEC DBO.TT_BACKUP";
        try{
            PreparedStatement ps=conn.prepareStatement(sql);
            ps.execute();
            ps.close();
            
            JOptionPane.showMessageDialog(this, "Sao lưu dữ liệu thành công!");
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Sao lưu dữ liệu không thành công!");
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btn_saoLuuActionPerformed

    private void btn_khoiPhucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_khoiPhucActionPerformed
        String sql="USE master " + "EXEC DBO.TT_RESTORE";
        try{
            PreparedStatement ps=conn.prepareStatement(sql);
            ps.executeUpdate();
            ps.close();
            this.conn.close();
            
            
            this.setVisible(false);
            KhuDat kd=new KhuDat();
            kd.setVisible(true);
            JOptionPane.showMessageDialog(this, "Khôi phục dữ liệu thành công!");
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Khôi phục dữ liệu không thành công!");
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btn_khoiPhucActionPerformed

    private void QuaylaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuaylaiActionPerformed
        // TODO add your handling code here:
                 this.setVisible(false);
            ChonLua da=new ChonLua();
            da.setVisible(true);
    }//GEN-LAST:event_QuaylaiActionPerformed

    public int timKiem(String maKD)
    {
        int kt=1;
        String sql1="SELECT * FROM KHUDAT";
        try{
            PreparedStatement ps1=conn.prepareStatement(sql1);
            ResultSet rs=ps1.executeQuery();
            while(rs.next())
            {
                if(maKD.equals(rs.getString("MAKD")))
                {
                   return kt; 
                }
                kt++;
            }
            rs.close();
            ps1.close();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        return 0;
    }
    
    public int nhapFileThemMoi(String url)
    {
        int kq=0;
        try{
            File f = new File(url);
            if(f.exists())
            {
                try(BufferedReader br=new BufferedReader(new FileReader(f)))
                {
                    String value;
                    while((value=br.readLine())!=null)
                    {
                        StringTokenizer stk=new StringTokenizer(value,";");
                        String maKD=stk.nextToken();
                        String chuSH=stk.nextToken();
                        String maDA=stk.nextToken();

                        Vector r=new Vector();
                        r.add(maKD);
                        r.add(chuSH);
                        r.add(maDA);
                        nd.add(r);
                        kq++;
                    }
                }
                catch(Exception ex)
                {
                    ex.printStackTrace();
                }
            }
            return kq;
        }
        catch(Exception e){
            e.printStackTrace();
            return kq;
        }
    }
    
    public int kiemTraMDAExists(String maKD)
    {
        int kt=0;
        String sql1="SELECT * FROM KHUDAT";
        try{
            PreparedStatement ps1=conn.prepareStatement(sql1);
            ResultSet rs=ps1.executeQuery();
            while(rs.next())
            {
                if(maKD.equals(rs.getString("MAKD")))
                {
                    kt++;
                }
            }
            rs.close();
            ps1.close();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        return kt;
    }
    
    public int nhapDataVaoSQL(int x)
    {
        int kq=0;
        int kt;
        if(x!=0)
        {
            for(int i=0;i<table_kq.getRowCount();i++)
            {
                String maKD = (String) table_kq.getValueAt(i, 0);
                String chuSH = (String) table_kq.getValueAt(i, 1);
                String maDA = (String) table_kq.getValueAt(i, 2);
                kt=kiemTraMDAExists(maKD);
                if(kt==0)
                {
                    String sql="INSERT INTO KHUDAT VALUES(?,?,?)";
                    try{
                        PreparedStatement ps=conn.prepareStatement(sql);
                        ps.setString(1, maKD);
                        ps.setString(2, chuSH);
                        ps.setString(3,maDA);

                        ps.executeUpdate();
                        ps.close();
                        kq++;
                    }
                    catch(Exception e)
                    {
                        e.printStackTrace(); 
                    }
                }
                
                
            }
        }
        else{
            JOptionPane.showMessageDialog(this,"Không có dữ liệu mới !");
        }
                
        return kq;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KhuDat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KhuDat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KhuDat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KhuDat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KhuDat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Quaylai;
    private javax.swing.JButton btn_khoiPhuc;
    private javax.swing.JButton btn_lamMoi;
    private javax.swing.JButton btn_removeAll;
    private javax.swing.JButton btn_saoLuu;
    private javax.swing.JButton but_capnhat;
    private javax.swing.JButton but_dong;
    private javax.swing.JButton but_nhapfile;
    private javax.swing.JButton but_nhapfile1;
    private javax.swing.JButton but_them;
    private javax.swing.JButton but_timkiem;
    private javax.swing.JButton but_xoa;
    private javax.swing.JButton but_xuatfile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_kq;
    private javax.swing.JTextField txt_chusohuu;
    private javax.swing.JTextField txt_maduan;
    private javax.swing.JTextField txt_makd;
    // End of variables declaration//GEN-END:variables
}
