/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Types;
import java.util.StringTokenizer;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LeLuuHoangNhan
 */
public class KhachHang extends javax.swing.JFrame {
    private Connection conn;
   
    Vector nd=new Vector();
    Vector td=new Vector();
    
    public KhachHang() {
        initComponents();
        this.setVisible(false);
        txt_soLuong_KH.setEnabled(false);
        txt_maKH_Max.setEnabled(false);
        txt_duAn_Max.setEnabled(false);
        
        td.add("MaKH");
        td.add("TenKH");
        td.add("Ngay Sinh");
        td.add("Gioi Tinh");
        td.add("NgayMua_Thue");
        td.add("Ma Du An");
        table_kq.setModel(new DefaultTableModel(nd,td));
        
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            conn=DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databasename=DB_QLDA;"
                    + "username=sa;password=1321");
            docdata();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        but_nhapfile1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_maKH = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_hotenKH = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_ngaysinhKH = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_gioitinhKH = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_ngaymuathueKH = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_maduanKH = new javax.swing.JTextField();
        but_capnhatKH = new javax.swing.JButton();
        but_themKH = new javax.swing.JButton();
        but_xoaKH = new javax.swing.JButton();
        but_timkiemKH = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_kq = new javax.swing.JTable();
        but_xuatfile = new javax.swing.JButton();
        but_nhapfile = new javax.swing.JButton();
        but_dong = new javax.swing.JButton();
        btn_lamMoi = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_soLuong_KH = new javax.swing.JTextField();
        txt_maKH_Max = new javax.swing.JTextField();
        txt_duAn_Max = new javax.swing.JTextField();
        btn_khoiPhuc = new javax.swing.JButton();
        btn_saoLuu = new javax.swing.JButton();
        btn_removeAll = new javax.swing.JButton();
        QuayLai = new javax.swing.JButton();

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 204));
        jLabel8.setText("@Bản quyền thuộc Lê Lưu Hoàng Nhân + Nguyễn Duy Thịnh");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        but_nhapfile1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        but_nhapfile1.setText("Nhập file.txt");
        but_nhapfile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_nhapfile1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("QUẢN LÝ KHÁCH HÀNG");

        jLabel2.setText("Mã KH :");

        jLabel3.setText("Họ tên :");

        jLabel4.setText("Ngày sinh :");

        jLabel5.setText("Giới tính :");

        jLabel6.setText("Ngày Mua_Thuê :");

        jLabel7.setText("Mã dự án :");

        but_capnhatKH.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        but_capnhatKH.setText("Cập nhật");
        but_capnhatKH.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        but_capnhatKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_capnhatKHActionPerformed(evt);
            }
        });

        but_themKH.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        but_themKH.setText("Thêm Mới");
        but_themKH.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        but_themKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_themKHActionPerformed(evt);
            }
        });

        but_xoaKH.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        but_xoaKH.setText("Xóa");
        but_xoaKH.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        but_xoaKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_xoaKHActionPerformed(evt);
            }
        });

        but_timkiemKH.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        but_timkiemKH.setText("Tìm kiếm");
        but_timkiemKH.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        but_timkiemKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_timkiemKHActionPerformed(evt);
            }
        });

        table_kq.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        table_kq.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        table_kq.setToolTipText("");
        table_kq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                table_kqMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(table_kq);

        but_xuatfile.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        but_xuatfile.setText("Xuất file.txt");
        but_xuatfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_xuatfileActionPerformed(evt);
            }
        });

        but_nhapfile.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        but_nhapfile.setText("Nhập file.txt");
        but_nhapfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_nhapfileActionPerformed(evt);
            }
        });

        but_dong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        but_dong.setText("Đóng");
        but_dong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                but_dongMouseClicked(evt);
            }
        });

        btn_lamMoi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_lamMoi.setText("Làm mới");
        btn_lamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lamMoiActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thống kê", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 255));
        jLabel9.setText("Số lượng KH hiện tại:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 255));
        jLabel11.setText("Mã KH giao dịch nhiều nhất:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 255));
        jLabel10.setText("Dự án KH quan tâm nhiều nhất:");

        txt_soLuong_KH.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_soLuong_KH.setForeground(new java.awt.Color(255, 0, 51));

        txt_maKH_Max.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_maKH_Max.setForeground(new java.awt.Color(255, 0, 51));

        txt_duAn_Max.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_duAn_Max.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_maKH_Max, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                            .addComponent(txt_soLuong_KH))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_duAn_Max)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_soLuong_KH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txt_maKH_Max, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_duAn_Max, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        btn_khoiPhuc.setBackground(new java.awt.Color(204, 255, 102));
        btn_khoiPhuc.setText("Khôi phục");
        btn_khoiPhuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_khoiPhucActionPerformed(evt);
            }
        });

        btn_saoLuu.setBackground(new java.awt.Color(255, 204, 102));
        btn_saoLuu.setText("Sao lưu");
        btn_saoLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saoLuuActionPerformed(evt);
            }
        });

        btn_removeAll.setBackground(new java.awt.Color(255, 0, 0));
        btn_removeAll.setText("Remove All");
        btn_removeAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removeAllActionPerformed(evt);
            }
        });

        QuayLai.setText("Quay lại");
        QuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuayLaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(but_xuatfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_saoLuu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(but_nhapfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_khoiPhuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_lamMoi, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(btn_removeAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(QuayLai)
                        .addGap(18, 18, 18)
                        .addComponent(but_dong, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_maKH, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                            .addComponent(txt_hotenKH, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_ngaysinhKH, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txt_ngaymuathueKH, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_maduanKH, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_gioitinhKH, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(but_capnhatKH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but_themKH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but_xoaKH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but_timkiemKH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(108, 108, 108))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(210, 210, 210))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_gioitinhKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txt_maKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_hotenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(but_themKH, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_ngaysinhKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(but_capnhatKH, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_ngaymuathueKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(but_xoaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_maduanKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but_timkiemKH, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_khoiPhuc)
                            .addComponent(btn_saoLuu)
                            .addComponent(btn_removeAll))
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_lamMoi)
                            .addComponent(but_nhapfile)
                            .addComponent(but_xuatfile)
                            .addComponent(but_dong)
                            .addComponent(QuayLai))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void docdata()
    {
        String sql="SELECT * FROM KHACHHANG";
        try{
            PreparedStatement ps=conn.prepareStatement(sql);
            ResultSet rs=ps.executeQuery();
            while(rs.next())
            {
                String maKH=rs.getString(1);
                String tenKH=rs.getString(2);
                String ngaySinh=rs.getDate(3).toString();
                String gioiTinh=rs.getString(4);
                String ngayMua_Thue=rs.getString(5).toString();
                String maDuAn=rs.getString(6);
                
                Vector r=new Vector();
                r.add(maKH);
                r.add(tenKH);
                r.add(ngaySinh);
                r.add(gioiTinh);
                r.add(ngayMua_Thue);
                r.add(maDuAn);
                
                nd.add(r);
                table_kq.setModel(new DefaultTableModel(nd,td));
            }
            rs.close();
            ps.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "Doc du lieu loi !");
            e.printStackTrace();
        }
        
        
        int dem_KH=goi_Ham_DemSL_SK();
        txt_soLuong_KH.setText(String.valueOf(dem_KH));
        
        String maKH_GD_Max=goiHam_TimKH_GiaoDichMax();
        txt_maKH_Max.setText(maKH_GD_Max);
        
        String tenDA_GD_Max=goiHam_LayTenDA_GiaoDichMax();
        txt_duAn_Max.setText(tenDA_GD_Max);
        
    }
    
    public int goi_Ham_DemSL_SK()
    {
        int sl=0;
        String sql="{?=CALL HAM_DEMSO_KH()}";
        try{
            PreparedStatement ps=conn.prepareStatement(sql); 
            CallableStatement cs=ps.getConnection().prepareCall(sql);
            cs.registerOutParameter(1, Types.INTEGER);
            cs.execute();
            
            sl=cs.getInt(1);
            cs.close();
            ps.close();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        return sl;
    }
    
    public String goiHam_TimKH_GiaoDichMax()
    {
        String maKH="";
        String sql="{?=CALL HAM_LAY_MAKH_GIAODICH_MAX()}";
        try{
            PreparedStatement ps=conn.prepareStatement(sql); 
            CallableStatement cs=ps.getConnection().prepareCall(sql);
            cs.registerOutParameter(1, Types.VARCHAR);
            cs.execute();
            
            maKH=cs.getString(1);
            cs.close();
            ps.close();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        return maKH;
    }
    
    public String goiHam_LayTenDA_GiaoDichMax()
    {
        String tenDA="";
        String sql="{?=CALL HAM_LAY_TENDA_GIAODICH_MAX()}";
        try{
            PreparedStatement ps=conn.prepareStatement(sql); 
            CallableStatement cs=ps.getConnection().prepareCall(sql);
            cs.registerOutParameter(1, Types.NVARCHAR);
            cs.execute();
            
            tenDA=cs.getNString(1);
            cs.close();
            ps.close();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        return tenDA;
    }
            
    
    private void but_capnhatKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_capnhatKHActionPerformed
        int row=table_kq.getSelectedRow();
        String maKH=table_kq.getValueAt(row, 0).toString();
        String tenKH=table_kq.getValueAt(row, 1).toString();
        String ngaySinh=table_kq.getValueAt(row, 2).toString();
        String gioiTinh=table_kq.getValueAt(row, 3).toString();
        String ngayMua_Thue=table_kq.getValueAt(row, 4).toString();
        String maDuAn=table_kq.getValueAt(row, 5).toString();
        
        String maKH1=txt_maKH.getText().toString();
        String tenKH1=txt_hotenKH.getText().toString();
        String ngaySinh1=txt_ngaysinhKH.getText().toString();
        String gioiTinh1=txt_gioitinhKH.getText().toString();
        String ngayMua_Thue1=txt_ngaymuathueKH.getText().toString();
        String maDuAn1=txt_maduanKH.getText().toString();
        
        if(maKH1.equals("")||tenKH1.equals("")||ngaySinh1.equals("")||gioiTinh1.equals("")||ngayMua_Thue1.equals("")||maDuAn1.equals(""))
        {
            JOptionPane.showMessageDialog(this,"Không được bỏ trống mục nào phía trên!");
        }
        else
        {
            int kt=kt_maKH_HopLe(maKH1);
            if(kt!=0)
            {       
                String sql="UPDATE KHACHHANG " + "SET MAKH=?, HOTEN=?, NGAYSINH=?, GTINH=?, NGAYMUA_THUE=?, MADUAN=? " 
                        +"WHERE MAKH=? AND HOTEN=? AND NGAYSINH=? AND GTINH=? AND NGAYMUA_THUE=? AND MADUAN=?";

                try{
                    PreparedStatement ps=conn.prepareStatement(sql);
                    ps.setString(1,maKH1);
                    ps.setString(2,tenKH1);
                    ps.setString(3,ngaySinh1);
                    ps.setString(4,gioiTinh1);
                    ps.setString(5,ngayMua_Thue1);
                    ps.setString(6,maDuAn1);

                    ps.setString(7,maKH);
                    ps.setString(8,tenKH);
                    ps.setString(9,ngaySinh);
                    ps.setString(10,gioiTinh);
                    ps.setString(11,ngayMua_Thue);
                    ps.setString(12,maDuAn);

                    ps.executeUpdate();
                    ps.close();
                    this.setVisible(false);
                    KhachHang kh=new KhachHang();
                    kh.setVisible(true);
                    JOptionPane.showMessageDialog(this,"Cập nhật thành công !");
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(this,"Cập nhật không thành công !");
                    e.printStackTrace();
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Mã KH không hợp lệ!");
            }
        }
    }//GEN-LAST:event_but_capnhatKHActionPerformed

    public int kt_maKH_HopLe(String maKH)
    {
        for(int i=0;i<maKH.length();i++)
        {
            char c=maKH.charAt(i);
            if(i==0 || i==1)
            {
                if(i==0)
                {
                    if(c!='K')
                        return 0;
                }
                else
                {
                    if(c!='H')
                        return 0;
                }   
            }
            else
            {
                if(c<'0'||c>'9')
                    return 0;
            }
        }
        return 1;
    }
    
    private void but_themKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_themKHActionPerformed
        String maKH=txt_maKH.getText().toString();
        String tenKH=txt_hotenKH.getText().toString();
        String ngaySinh=txt_ngaysinhKH.getText().toString();
        String gioiTinh=txt_gioitinhKH.getText().toString();
        String ngayMua_Thue=txt_ngaymuathueKH.getText().toString();
        String maDuAn=txt_maduanKH.getText().toString();
        
        if(maKH.equals("")||tenKH.equals("")||ngaySinh.equals("")||gioiTinh.equals("")||ngayMua_Thue.equals("")||maDuAn.equals(""))
        {
            JOptionPane.showMessageDialog(this,"Không được bỏ trống mục nào phía trên!");
        }
        else
        {   
            int kt=kt_maKH_HopLe(maKH);
            if(kt!=0)
            {
                String sql="INSERT INTO KHACHHANG " + "VALUES(?,?,?,?,?,?)";
                try{
                    PreparedStatement ps=conn.prepareStatement(sql);
                    ps.setString(1,maKH);
                    ps.setString(2,tenKH);
                    ps.setString(3,ngaySinh);
                    ps.setString(4,gioiTinh);
                    ps.setString(5,ngayMua_Thue);
                    ps.setString(6,maDuAn);

                    ps.executeUpdate();
                    ps.close();
                    this.setVisible(false);
                    KhachHang kh=new KhachHang();
                    kh.setVisible(true);
                    JOptionPane.showMessageDialog(this,"Thêm mới thành công !");
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(this,"Thêm mới không thành công !");
                    e.printStackTrace();
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Mã KH không hợp lệ.");
            }
        }
    }//GEN-LAST:event_but_themKHActionPerformed

    private void but_xoaKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_xoaKHActionPerformed

        String maKH=txt_maKH.getText().toString();
        String maDA=txt_maduanKH.getText().toString();
        if(maKH.equals("")||maDA.equals(""))
        {
            JOptionPane.showMessageDialog(this,"Không được bỏ trống MaDuAn, MaKH!");
        }
        else
        {
            String sql="DELETE FROM KHACHHANG WHERE MAKH=? AND MADUAN=?";
            try{
                PreparedStatement ps=conn.prepareStatement(sql);
                ps.setString(1,maKH);
                ps.setString(2,maDA);

                ps.executeUpdate();
                ps.close();
                this.setVisible(false);
                KhachHang kh=new KhachHang();
                kh.setVisible(true);
                JOptionPane.showMessageDialog(this,"Xóa dữ liệu thành công !");
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this,"Xóa dữ liệu không thành công !");
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_but_xoaKHActionPerformed

    private void but_timkiemKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_timkiemKHActionPerformed
        String maKH=txt_maKH.getText().toString();
        String maDA=txt_maduanKH.getText().toString();
        if(maKH.equals("") || maDA.equals(""))
        {
            JOptionPane.showMessageDialog(this,"MaKH - Ma Du An =>>> Không được bỏ trống !");
        }
        else{
            int tk=timKiem(maKH, maDA);
            if(tk!=0)
            {
                JOptionPane.showMessageDialog(this,"Tìm thấy tại vị trí thứ : " + tk);
            }
            else{
                JOptionPane.showMessageDialog(this,"Không tìm thấy !");
            }
        }
    }//GEN-LAST:event_but_timkiemKHActionPerformed

    public int timKiem(String maKH, String maDA)
    {
        int kt=1;
        String sql1="SELECT * FROM KHACHHANG";
        try{
            PreparedStatement ps1=conn.prepareStatement(sql1);
            ResultSet rs=ps1.executeQuery();
            while(rs.next())
            {
                if(maKH.equals(rs.getString("MAKH")) && maDA.equals(rs.getString("MADUAN")))
                {
                   return kt; 
                }
                kt++;
            }
            rs.close();
            ps1.close();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        return 0;
    }
    
    private void but_dongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_but_dongMouseClicked
        JFrame f=new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(f, "Bạn có muốn thoát chương trình ?", "Thông báo", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
            System.exit(0);
    }//GEN-LAST:event_but_dongMouseClicked

    private void but_xuatfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_xuatfileActionPerformed
        int k=1;
        try{
            File f=new File("E:/KHACHHANG.TXT");
            while(f.exists())
            {
                f=new File("E:/KHACHHANG" + "(" + k + ")" + ".TXT");
                k++;
            }
            FileWriter fw=new FileWriter(f);
            for(int i=0;i<table_kq.getRowCount();i++)
            {
                  fw.write((String) table_kq.getValueAt(i, 0)+";");
                  fw.write((String) table_kq.getValueAt(i, 1)+";");
                  fw.write((String) table_kq.getValueAt(i, 2)+";");
                  fw.write((String) table_kq.getValueAt(i, 3)+";");
                  fw.write((String) table_kq.getValueAt(i, 4)+";");
                  fw.write((String) table_kq.getValueAt(i, 5));
                  if(i+1!=table_kq.getRowCount())
                      fw.write("\n");
            }
            fw.close();
            JOptionPane.showMessageDialog(this, "Xuat file thanh cong !");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "Loi xuat file !");
            e.printStackTrace();
        }
    }//GEN-LAST:event_but_xuatfileActionPerformed

    private void but_nhapfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_nhapfileActionPerformed

            int nhapFile=this.nhapFileMoi("E:/KHACHHANG.TXT");
            if(nhapFile!=0)
            {
                int nhap=this.nhapDataVaoSQL();
                if(nhap!=0)
                {
                    this.setVisible(false);
                    KhachHang kh=new KhachHang();
                    kh.setVisible(true);
                    JOptionPane.showMessageDialog(this,"Nhap file thanh cong !");
                }
                else{
                    JOptionPane.showMessageDialog(this,"Nhap file khong thanh cong !");
                }
            }
            else{
                JOptionPane.showMessageDialog(this,"Nhap file.txt vao java khong thanh cong !");
            }
            
    }//GEN-LAST:event_but_nhapfileActionPerformed

    private void table_kqMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_kqMousePressed
        int row=table_kq.getSelectedRow();
        txt_maKH.setText((String) table_kq.getValueAt(row, 0));
        txt_hotenKH.setText((String) table_kq.getValueAt(row, 1));
        txt_ngaysinhKH.setText((String) String.valueOf(table_kq.getValueAt(row, 2)));
        txt_gioitinhKH.setText((String) table_kq.getValueAt(row, 3));
        txt_ngaymuathueKH.setText((String) String.valueOf(table_kq.getValueAt(row, 4)));
        txt_maduanKH.setText((String) table_kq.getValueAt(row, 5));
    }//GEN-LAST:event_table_kqMousePressed

    private void but_nhapfile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_nhapfile1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_but_nhapfile1ActionPerformed

    private void btn_lamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lamMoiActionPerformed
        this.setVisible(false);
        KhachHang kh=new KhachHang();
        kh.setVisible(true);
    }//GEN-LAST:event_btn_lamMoiActionPerformed

    private void btn_removeAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeAllActionPerformed
        String sql="DELETE FROM KHACHHANG";
        try
        {
            PreparedStatement ps=conn.prepareStatement(sql);
            ps.executeUpdate();
            ps.close();
            
            this.setVisible(false);
            KhachHang kh=new KhachHang();
            kh.setVisible(true);
            JOptionPane.showMessageDialog(this, "Remove All thành công!");
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Remove All không thành công!");
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btn_removeAllActionPerformed

    private void btn_saoLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saoLuuActionPerformed
        String sql="EXEC DBO.TT_BACKUP";
        try{
            PreparedStatement ps=conn.prepareStatement(sql);
            ps.execute();
            ps.close();
            
            JOptionPane.showMessageDialog(this, "Sao lưu dữ liệu thành công!");
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Sao lưu dữ liệu không thành công!");
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btn_saoLuuActionPerformed

    private void btn_khoiPhucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_khoiPhucActionPerformed
        String sql="USE master " + "EXEC DBO.TT_RESTORE";
        try{
            PreparedStatement ps=conn.prepareStatement(sql);
            ps.executeUpdate();
            ps.close();
            this.conn.close();
            
            
            this.setVisible(false);
            KhachHang kh=new KhachHang();
            kh.setVisible(true);
            JOptionPane.showMessageDialog(this, "Khôi phục dữ liệu thành công!");
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Khôi phục dữ liệu không thành công!");
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btn_khoiPhucActionPerformed

    private void QuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuayLaiActionPerformed
                    this.setVisible(false);
            ChonLua da=new ChonLua();
            da.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_QuayLaiActionPerformed


    
    public int nhapFileMoi(String url)
    {
        int kq=0;
        try{
            File f = new File(url);
            if(f.exists())
            {
                try(BufferedReader br=new BufferedReader(new FileReader(f)))
                {
                    String value;
                    while((value=br.readLine())!=null)
                    {
                        StringTokenizer stk=new StringTokenizer(value,";");
                        String maKH=stk.nextToken();
                        String tenKH=stk.nextToken();
                        String ngaySinh=stk.nextToken();
                        String gioiTinh=stk.nextToken();
                        String ngayMua_Thue=stk.nextToken();
                        String maDuAn=stk.nextToken();

                        Vector r=new Vector();
                        r.add(maKH);
                        r.add(tenKH);
                        r.add(ngaySinh);
                        r.add(gioiTinh);
                        r.add(ngayMua_Thue);
                        r.add(maDuAn);
                        nd.add(r);
                        kq++;
                    }
                }
                catch(Exception ex)
                {
                    ex.printStackTrace();
                }
            }
            return kq;
        }
        catch(Exception e){
            e.printStackTrace();
            return kq;
        }
    }
    
    public int nhapDataVaoSQL()
    {
        int kq=0;
        for(int i=0;i<table_kq.getRowCount();i++)
        {
            String maKH = (String) table_kq.getValueAt(i, 0);
            String tenKH = (String) table_kq.getValueAt(i, 1);
            String ngaySinh = (String) table_kq.getValueAt(i, 2);
            String gioiTinh = (String) table_kq.getValueAt(i, 3);
            String ngayMua_Thue = (String) table_kq.getValueAt(i, 4);
            String maDA = (String) table_kq.getValueAt(i, 5);

            String sql="INSERT INTO KHACHHANG VALUES(?,?,?,?,?,?)";
            try{
                PreparedStatement ps=conn.prepareStatement(sql);
                ps.setString(1, maKH);
                ps.setString(2, tenKH);
                ps.setString(3,ngaySinh);
                ps.setString(4, gioiTinh);
                ps.setString(5,ngayMua_Thue);
                ps.setString(6, maDA);

                ps.executeUpdate();
                ps.close();
                kq++;
            }
            catch(Exception e)
            {
                e.printStackTrace(); 
            }
        }
        return kq;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KhachHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton QuayLai;
    private javax.swing.JButton btn_khoiPhuc;
    private javax.swing.JButton btn_lamMoi;
    private javax.swing.JButton btn_removeAll;
    private javax.swing.JButton btn_saoLuu;
    private javax.swing.JButton but_capnhatKH;
    private javax.swing.JButton but_dong;
    private javax.swing.JButton but_nhapfile;
    private javax.swing.JButton but_nhapfile1;
    private javax.swing.JButton but_themKH;
    private javax.swing.JButton but_timkiemKH;
    private javax.swing.JButton but_xoaKH;
    private javax.swing.JButton but_xuatfile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTable table_kq;
    private javax.swing.JTextField txt_duAn_Max;
    private javax.swing.JTextField txt_gioitinhKH;
    private javax.swing.JTextField txt_hotenKH;
    private javax.swing.JTextField txt_maKH;
    private javax.swing.JTextField txt_maKH_Max;
    private javax.swing.JTextField txt_maduanKH;
    private javax.swing.JTextField txt_ngaymuathueKH;
    private javax.swing.JTextField txt_ngaysinhKH;
    private javax.swing.JTextField txt_soLuong_KH;
    // End of variables declaration//GEN-END:variables
}
