// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestHoaDonBanHang
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethod_ThemHD - Use 'RecordedMethod_ThemHDParams' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod_ThemHD()
        {
            #region Variable Declarations
            WinButton uIBtnThemButton = this.UIQL_CuaHangVatLieuXayWindow.UIHoaDonXuatWindow.UIBtnThemWindow.UIBtnThemButton;
            WinEdit uITxtMaHDEdit = this.UIQL_CuaHangVatLieuXayWindow.UIHoaDonXuatWindow.UITxtMaHDWindow.UITxtMaHDEdit;
            WinComboBox uIĐơnvịtínhComboBox = this.UIQL_CuaHangVatLieuXayWindow.UIHoaDonXuatWindow.UICboKhachHangWindow.UIĐơnvịtínhComboBox;
            WinComboBox uICboTenNVComboBox = this.UIQL_CuaHangVatLieuXayWindow.UIHoaDonXuatWindow.UICboTenNVWindow.UICboTenNVComboBox;
            WinDateTimePicker uIDtpNgayLapDateTimePicker = this.UIQL_CuaHangVatLieuXayWindow.UIHoaDonXuatWindow.UIDtpNgayLapWindow.UIDtpNgayLapDateTimePicker;
            WinComboBox uICboTenSanPhamComboBox = this.UIQL_CuaHangVatLieuXayWindow.UIHoaDonXuatWindow.UICboTenSanPhamWindow.UICboTenSanPhamComboBox;
            WinEdit uITxtDonGiaEdit = this.UIQL_CuaHangVatLieuXayWindow.UIHoaDonXuatWindow.UITxtDonGiaWindow.UITxtDonGiaEdit;
            WinComboBox uICboDVTComboBox = this.UIQL_CuaHangVatLieuXayWindow.UIHoaDonXuatWindow.UICboDVTWindow.UICboDVTComboBox;
            WinEdit uITxtSoLuongEdit = this.UIQL_CuaHangVatLieuXayWindow.UIHoaDonXuatWindow.UITxtSoLuongWindow.UITxtSoLuongEdit;
            WinEdit uITxtThanhTienEdit = this.UIQL_CuaHangVatLieuXayWindow.UIHoaDonXuatWindow.UITxtThanhTienWindow.UITxtThanhTienEdit;
            WinButton uIBtnSaveButton = this.UIQL_CuaHangVatLieuXayWindow.UIHoaDonXuatWindow.UIBtnSaveWindow.UIBtnSaveButton;
            WinEdit uILblThongBaoEdit = this.UIQL_CuaHangVatLieuXayWindow.UIHoaDonXuatWindow.UIThongBaoWindow.UILblThongBaoEdit;
            #endregion

            // Click 'btnThem' button
            Mouse.Click(uIBtnThemButton, new Point(32, 32));

            // Type 'HDX8' in 'txtMaHD' text box
            uITxtMaHDEdit.Text = this.RecordedMethod_ThemHDParams.UITxtMaHDEditText;

            // Select 'Huỳnh Quốc Tuấn' in 'Đơn vị tính' combo box
            uIĐơnvịtínhComboBox.SelectedItem = this.RecordedMethod_ThemHDParams.UIĐơnvịtínhComboBoxSelectedItem;

            // Select 'Trần Quang Đại' in 'cboTenNV' combo box
            uICboTenNVComboBox.SelectedItem = this.RecordedMethod_ThemHDParams.UICboTenNVComboBoxSelectedItem;

            // Select '18/05/2022' in 'dtpNgayLap' date time picker
            uIDtpNgayLapDateTimePicker.DateTimeAsString = this.RecordedMethod_ThemHDParams.UIDtpNgayLapDateTimePickerDateTimeAsString;

            // Select 'Xi Măng Vicem Hà Tiên' in 'cboTenSanPham' combo box
            uICboTenSanPhamComboBox.SelectedItem = this.RecordedMethod_ThemHDParams.UICboTenSanPhamComboBoxSelectedItem;

            // Type '100' in 'txtDonGia' text box
            uITxtDonGiaEdit.Text = this.RecordedMethod_ThemHDParams.UITxtDonGiaEditText;

            // Select 'M2' in 'cboDVT' combo box
            uICboDVTComboBox.SelectedItem = this.RecordedMethod_ThemHDParams.UICboDVTComboBoxSelectedItem;

            // Type '50' in 'txtSoLuong' text box
            uITxtSoLuongEdit.Text = this.RecordedMethod_ThemHDParams.UITxtSoLuongEditText;

            // Click 'txtThanhTien' text box
            Mouse.Click(uITxtThanhTienEdit, new Point(105, 10));

            // Click 'btnSave' button
            Mouse.Click(uIBtnSaveButton, new Point(45, 19));

            // Click 'lblThongBao' text box
            Mouse.Click(uILblThongBaoEdit, new Point(68, 13));
        }
        
        /// <summary>
        /// AssertMethod_ThemHD - Use 'AssertMethod_ThemHDExpectedValues' to pass parameters into this method.
        /// </summary>
        public void AssertMethod_ThemHD()
        {
            #region Variable Declarations
            WinEdit uILblThongBaoEdit = this.UIQL_CuaHangVatLieuXayWindow.UIHoaDonXuatWindow.UIThongBaoWindow.UILblThongBaoEdit;
            #endregion

            // Verify that the 'ControlName' property of 'lblThongBao' text box equals 'Thanh cong'
            Assert.AreEqual(this.AssertMethod_ThemHDExpectedValues.UILblThongBaoEditControlName, uILblThongBaoEdit.Text);
        }
        
        #region Properties
        public virtual RecordedMethod_ThemHDParams RecordedMethod_ThemHDParams
        {
            get
            {
                if ((this.mRecordedMethod_ThemHDParams == null))
                {
                    this.mRecordedMethod_ThemHDParams = new RecordedMethod_ThemHDParams();
                }
                return this.mRecordedMethod_ThemHDParams;
            }
        }
        
        public virtual AssertMethod_ThemHDExpectedValues AssertMethod_ThemHDExpectedValues
        {
            get
            {
                if ((this.mAssertMethod_ThemHDExpectedValues == null))
                {
                    this.mAssertMethod_ThemHDExpectedValues = new AssertMethod_ThemHDExpectedValues();
                }
                return this.mAssertMethod_ThemHDExpectedValues;
            }
        }
        
        public UIQL_CuaHangVatLieuXayWindow UIQL_CuaHangVatLieuXayWindow
        {
            get
            {
                if ((this.mUIQL_CuaHangVatLieuXayWindow == null))
                {
                    this.mUIQL_CuaHangVatLieuXayWindow = new UIQL_CuaHangVatLieuXayWindow();
                }
                return this.mUIQL_CuaHangVatLieuXayWindow;
            }
        }
        #endregion
        
        #region Fields
        private RecordedMethod_ThemHDParams mRecordedMethod_ThemHDParams;
        
        private AssertMethod_ThemHDExpectedValues mAssertMethod_ThemHDExpectedValues;
        
        private UIQL_CuaHangVatLieuXayWindow mUIQL_CuaHangVatLieuXayWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod_ThemHD'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class RecordedMethod_ThemHDParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'HDX8' in 'txtMaHD' text box
        /// </summary>
        public string UITxtMaHDEditText = "HDX8";
        
        /// <summary>
        /// Select 'Huỳnh Quốc Tuấn' in 'Đơn vị tính' combo box
        /// </summary>
        public string UIĐơnvịtínhComboBoxSelectedItem = "Huỳnh Quốc Tuấn";
        
        /// <summary>
        /// Select 'Trần Quang Đại' in 'cboTenNV' combo box
        /// </summary>
        public string UICboTenNVComboBoxSelectedItem = "Trần Quang Đại";
        
        /// <summary>
        /// Select '18/05/2022' in 'dtpNgayLap' date time picker
        /// </summary>
        public string UIDtpNgayLapDateTimePickerDateTimeAsString = "18-May-2022";
        
        /// <summary>
        /// Select 'Xi Măng Vicem Hà Tiên' in 'cboTenSanPham' combo box
        /// </summary>
        public string UICboTenSanPhamComboBoxSelectedItem = "Xi Măng Vicem Hà Tiên";
        
        /// <summary>
        /// Type '100' in 'txtDonGia' text box
        /// </summary>
        public string UITxtDonGiaEditText = "100";
        
        /// <summary>
        /// Select 'M2' in 'cboDVT' combo box
        /// </summary>
        public string UICboDVTComboBoxSelectedItem = "M2";
        
        /// <summary>
        /// Type '50' in 'txtSoLuong' text box
        /// </summary>
        public string UITxtSoLuongEditText = "50";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertMethod_ThemHD'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class AssertMethod_ThemHDExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'ControlName' property of 'lblThongBao' text box equals 'Thanh cong'
        /// </summary>
        public string UILblThongBaoEditControlName = "Thanh cong";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIQL_CuaHangVatLieuXayWindow : WinWindow
    {
        
        public UIQL_CuaHangVatLieuXayWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "QL_CuaHangVatLieuXayDung - [HoaDonXuat]";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("QL_CuaHangVatLieuXayDung - [HoaDonXuat]");
            #endregion
        }
        
        #region Properties
        public UIHoaDonXuatWindow UIHoaDonXuatWindow
        {
            get
            {
                if ((this.mUIHoaDonXuatWindow == null))
                {
                    this.mUIHoaDonXuatWindow = new UIHoaDonXuatWindow(this);
                }
                return this.mUIHoaDonXuatWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIHoaDonXuatWindow mUIHoaDonXuatWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIHoaDonXuatWindow : WinWindow
    {
        
        public UIHoaDonXuatWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "HoaDonXuat";
            this.WindowTitles.Add("QL_CuaHangVatLieuXayDung - [HoaDonXuat]");
            #endregion
        }
        
        #region Properties
        public UIBtnThemWindow UIBtnThemWindow
        {
            get
            {
                if ((this.mUIBtnThemWindow == null))
                {
                    this.mUIBtnThemWindow = new UIBtnThemWindow(this);
                }
                return this.mUIBtnThemWindow;
            }
        }
        
        public UITxtMaHDWindow UITxtMaHDWindow
        {
            get
            {
                if ((this.mUITxtMaHDWindow == null))
                {
                    this.mUITxtMaHDWindow = new UITxtMaHDWindow(this);
                }
                return this.mUITxtMaHDWindow;
            }
        }
        
        public UICboKhachHangWindow UICboKhachHangWindow
        {
            get
            {
                if ((this.mUICboKhachHangWindow == null))
                {
                    this.mUICboKhachHangWindow = new UICboKhachHangWindow(this);
                }
                return this.mUICboKhachHangWindow;
            }
        }
        
        public UICboTenNVWindow UICboTenNVWindow
        {
            get
            {
                if ((this.mUICboTenNVWindow == null))
                {
                    this.mUICboTenNVWindow = new UICboTenNVWindow(this);
                }
                return this.mUICboTenNVWindow;
            }
        }
        
        public UIDtpNgayLapWindow UIDtpNgayLapWindow
        {
            get
            {
                if ((this.mUIDtpNgayLapWindow == null))
                {
                    this.mUIDtpNgayLapWindow = new UIDtpNgayLapWindow(this);
                }
                return this.mUIDtpNgayLapWindow;
            }
        }
        
        public UICboTenSanPhamWindow UICboTenSanPhamWindow
        {
            get
            {
                if ((this.mUICboTenSanPhamWindow == null))
                {
                    this.mUICboTenSanPhamWindow = new UICboTenSanPhamWindow(this);
                }
                return this.mUICboTenSanPhamWindow;
            }
        }
        
        public UITxtDonGiaWindow UITxtDonGiaWindow
        {
            get
            {
                if ((this.mUITxtDonGiaWindow == null))
                {
                    this.mUITxtDonGiaWindow = new UITxtDonGiaWindow(this);
                }
                return this.mUITxtDonGiaWindow;
            }
        }
        
        public UICboDVTWindow UICboDVTWindow
        {
            get
            {
                if ((this.mUICboDVTWindow == null))
                {
                    this.mUICboDVTWindow = new UICboDVTWindow(this);
                }
                return this.mUICboDVTWindow;
            }
        }
        
        public UITxtSoLuongWindow UITxtSoLuongWindow
        {
            get
            {
                if ((this.mUITxtSoLuongWindow == null))
                {
                    this.mUITxtSoLuongWindow = new UITxtSoLuongWindow(this);
                }
                return this.mUITxtSoLuongWindow;
            }
        }
        
        public UITxtThanhTienWindow UITxtThanhTienWindow
        {
            get
            {
                if ((this.mUITxtThanhTienWindow == null))
                {
                    this.mUITxtThanhTienWindow = new UITxtThanhTienWindow(this);
                }
                return this.mUITxtThanhTienWindow;
            }
        }
        
        public UIBtnSaveWindow UIBtnSaveWindow
        {
            get
            {
                if ((this.mUIBtnSaveWindow == null))
                {
                    this.mUIBtnSaveWindow = new UIBtnSaveWindow(this);
                }
                return this.mUIBtnSaveWindow;
            }
        }
        
        public UIThongBaoWindow UIThongBaoWindow
        {
            get
            {
                if ((this.mUIThongBaoWindow == null))
                {
                    this.mUIThongBaoWindow = new UIThongBaoWindow(this);
                }
                return this.mUIThongBaoWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIBtnThemWindow mUIBtnThemWindow;
        
        private UITxtMaHDWindow mUITxtMaHDWindow;
        
        private UICboKhachHangWindow mUICboKhachHangWindow;
        
        private UICboTenNVWindow mUICboTenNVWindow;
        
        private UIDtpNgayLapWindow mUIDtpNgayLapWindow;
        
        private UICboTenSanPhamWindow mUICboTenSanPhamWindow;
        
        private UITxtDonGiaWindow mUITxtDonGiaWindow;
        
        private UICboDVTWindow mUICboDVTWindow;
        
        private UITxtSoLuongWindow mUITxtSoLuongWindow;
        
        private UITxtThanhTienWindow mUITxtThanhTienWindow;
        
        private UIBtnSaveWindow mUIBtnSaveWindow;
        
        private UIThongBaoWindow mUIThongBaoWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIBtnThemWindow : WinWindow
    {
        
        public UIBtnThemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnThem";
            this.WindowTitles.Add("QL_CuaHangVatLieuXayDung - [HoaDonXuat]");
            #endregion
        }
        
        #region Properties
        public WinButton UIBtnThemButton
        {
            get
            {
                if ((this.mUIBtnThemButton == null))
                {
                    this.mUIBtnThemButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIBtnThemButton.WindowTitles.Add("QL_CuaHangVatLieuXayDung - [HoaDonXuat]");
                    #endregion
                }
                return this.mUIBtnThemButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIBtnThemButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UITxtMaHDWindow : WinWindow
    {
        
        public UITxtMaHDWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtMaHD";
            this.WindowTitles.Add("QL_CuaHangVatLieuXayDung - [HoaDonXuat]");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtMaHDEdit
        {
            get
            {
                if ((this.mUITxtMaHDEdit == null))
                {
                    this.mUITxtMaHDEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtMaHDEdit.SearchProperties[WinEdit.PropertyNames.Name] = "HÓA ĐƠN BÁN";
                    this.mUITxtMaHDEdit.WindowTitles.Add("QL_CuaHangVatLieuXayDung - [HoaDonXuat]");
                    #endregion
                }
                return this.mUITxtMaHDEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtMaHDEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UICboKhachHangWindow : WinWindow
    {
        
        public UICboKhachHangWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "cboKhachHang";
            this.WindowTitles.Add("QL_CuaHangVatLieuXayDung - [HoaDonXuat]");
            #endregion
        }
        
        #region Properties
        public WinComboBox UIĐơnvịtínhComboBox
        {
            get
            {
                if ((this.mUIĐơnvịtínhComboBox == null))
                {
                    this.mUIĐơnvịtínhComboBox = new WinComboBox(this);
                    #region Search Criteria
                    this.mUIĐơnvịtínhComboBox.SearchProperties[WinComboBox.PropertyNames.Name] = "Đơn vị tính";
                    this.mUIĐơnvịtínhComboBox.WindowTitles.Add("QL_CuaHangVatLieuXayDung - [HoaDonXuat]");
                    #endregion
                }
                return this.mUIĐơnvịtínhComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUIĐơnvịtínhComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UICboTenNVWindow : WinWindow
    {
        
        public UICboTenNVWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "cboTenNV";
            this.WindowTitles.Add("QL_CuaHangVatLieuXayDung - [HoaDonXuat]");
            #endregion
        }
        
        #region Properties
        public WinComboBox UICboTenNVComboBox
        {
            get
            {
                if ((this.mUICboTenNVComboBox == null))
                {
                    this.mUICboTenNVComboBox = new WinComboBox(this);
                    #region Search Criteria
                    this.mUICboTenNVComboBox.WindowTitles.Add("QL_CuaHangVatLieuXayDung - [HoaDonXuat]");
                    #endregion
                }
                return this.mUICboTenNVComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUICboTenNVComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIDtpNgayLapWindow : WinWindow
    {
        
        public UIDtpNgayLapWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "dtpNgayLap";
            this.WindowTitles.Add("QL_CuaHangVatLieuXayDung - [HoaDonXuat]");
            #endregion
        }
        
        #region Properties
        public WinDateTimePicker UIDtpNgayLapDateTimePicker
        {
            get
            {
                if ((this.mUIDtpNgayLapDateTimePicker == null))
                {
                    this.mUIDtpNgayLapDateTimePicker = new WinDateTimePicker(this);
                    #region Search Criteria
                    this.mUIDtpNgayLapDateTimePicker.WindowTitles.Add("QL_CuaHangVatLieuXayDung - [HoaDonXuat]");
                    #endregion
                }
                return this.mUIDtpNgayLapDateTimePicker;
            }
        }
        #endregion
        
        #region Fields
        private WinDateTimePicker mUIDtpNgayLapDateTimePicker;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UICboTenSanPhamWindow : WinWindow
    {
        
        public UICboTenSanPhamWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "cboTenSanPham";
            this.WindowTitles.Add("QL_CuaHangVatLieuXayDung - [HoaDonXuat]");
            #endregion
        }
        
        #region Properties
        public WinComboBox UICboTenSanPhamComboBox
        {
            get
            {
                if ((this.mUICboTenSanPhamComboBox == null))
                {
                    this.mUICboTenSanPhamComboBox = new WinComboBox(this);
                    #region Search Criteria
                    this.mUICboTenSanPhamComboBox.WindowTitles.Add("QL_CuaHangVatLieuXayDung - [HoaDonXuat]");
                    #endregion
                }
                return this.mUICboTenSanPhamComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUICboTenSanPhamComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UITxtDonGiaWindow : WinWindow
    {
        
        public UITxtDonGiaWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtDonGia";
            this.WindowTitles.Add("QL_CuaHangVatLieuXayDung - [HoaDonXuat]");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtDonGiaEdit
        {
            get
            {
                if ((this.mUITxtDonGiaEdit == null))
                {
                    this.mUITxtDonGiaEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtDonGiaEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Số lượng";
                    this.mUITxtDonGiaEdit.WindowTitles.Add("QL_CuaHangVatLieuXayDung - [HoaDonXuat]");
                    #endregion
                }
                return this.mUITxtDonGiaEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtDonGiaEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UICboDVTWindow : WinWindow
    {
        
        public UICboDVTWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "cboDVT";
            this.WindowTitles.Add("QL_CuaHangVatLieuXayDung - [HoaDonXuat]");
            #endregion
        }
        
        #region Properties
        public WinComboBox UICboDVTComboBox
        {
            get
            {
                if ((this.mUICboDVTComboBox == null))
                {
                    this.mUICboDVTComboBox = new WinComboBox(this);
                    #region Search Criteria
                    this.mUICboDVTComboBox.WindowTitles.Add("QL_CuaHangVatLieuXayDung - [HoaDonXuat]");
                    #endregion
                }
                return this.mUICboDVTComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUICboDVTComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UITxtSoLuongWindow : WinWindow
    {
        
        public UITxtSoLuongWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtSoLuong";
            this.WindowTitles.Add("QL_CuaHangVatLieuXayDung - [HoaDonXuat]");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtSoLuongEdit
        {
            get
            {
                if ((this.mUITxtSoLuongEdit == null))
                {
                    this.mUITxtSoLuongEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtSoLuongEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Tên sản phẩm";
                    this.mUITxtSoLuongEdit.WindowTitles.Add("QL_CuaHangVatLieuXayDung - [HoaDonXuat]");
                    #endregion
                }
                return this.mUITxtSoLuongEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtSoLuongEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UITxtThanhTienWindow : WinWindow
    {
        
        public UITxtThanhTienWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtThanhTien";
            this.WindowTitles.Add("QL_CuaHangVatLieuXayDung - [HoaDonXuat]");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtThanhTienEdit
        {
            get
            {
                if ((this.mUITxtThanhTienEdit == null))
                {
                    this.mUITxtThanhTienEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtThanhTienEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Đơn giá";
                    this.mUITxtThanhTienEdit.WindowTitles.Add("QL_CuaHangVatLieuXayDung - [HoaDonXuat]");
                    #endregion
                }
                return this.mUITxtThanhTienEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtThanhTienEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIBtnSaveWindow : WinWindow
    {
        
        public UIBtnSaveWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnSave";
            this.WindowTitles.Add("QL_CuaHangVatLieuXayDung - [HoaDonXuat]");
            #endregion
        }
        
        #region Properties
        public WinButton UIBtnSaveButton
        {
            get
            {
                if ((this.mUIBtnSaveButton == null))
                {
                    this.mUIBtnSaveButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIBtnSaveButton.WindowTitles.Add("QL_CuaHangVatLieuXayDung - [HoaDonXuat]");
                    #endregion
                }
                return this.mUIBtnSaveButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIBtnSaveButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIThongBaoWindow : WinWindow
    {
        
        public UIThongBaoWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "lblThongBao";
            this.WindowTitles.Add("QL_CuaHangVatLieuXayDung - [HoaDonXuat]");
            #endregion
        }
        
        #region Properties
        public WinEdit UILblThongBaoEdit
        {
            get
            {
                if ((this.mUILblThongBaoEdit == null))
                {
                    this.mUILblThongBaoEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUILblThongBaoEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Cập nhật database";
                    this.mUILblThongBaoEdit.WindowTitles.Add("QL_CuaHangVatLieuXayDung - [HoaDonXuat]");
                    #endregion
                }
                return this.mUILblThongBaoEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUILblThongBaoEdit;
        #endregion
    }
}
