//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourDuLich.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=A111PC02\\CSSQL08;Initial Catalog=QL_TOURDULICH;Integrated Security=Tr" +
            "ue")]
        public string QL_TOURDULICHConnectionString {
            get {
                return ((string)(this["QL_TOURDULICHConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=A110PC35\\CSSQL08;Initial Catalog=QL_TOURDULICH;User ID=sa;Password=12" +
            "3")]
        public string QL_TOURDULICHConnectionString1 {
            get {
                return ((string)(this["QL_TOURDULICHConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LELUUHOANGNHAN;Initial Catalog=QL_TOURDULICH;User ID=sa;Password=123")]
        public string QL_TOURDULICHConnectionString2 {
            get {
                return ((string)(this["QL_TOURDULICHConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=A110PC04\\CSSQL08;Initial Catalog=QL_TOURDULICH;User ID=sa;Password=12" +
            "3")]
        public string QL_TOURDULICHConnectionString3 {
            get {
                return ((string)(this["QL_TOURDULICHConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-DOB5S88\\SQLEXPRESS;Initial Catalog=QL_TOURDULICH;Integrated S" +
            "ecurity=True")]
        public string QL_TOURDULICHConnectionString4 {
            get {
                return ((string)(this["QL_TOURDULICHConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=A105PC46\\CSSQL08;Initial Catalog=QL_TOURDULICH;Integrated Security=Tr" +
            "ue")]
        public string QL_TOURDULICHConnectionString5 {
            get {
                return ((string)(this["QL_TOURDULICHConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-VIPKLQVT\\SQLEXPRESS;Initial Catalog=QL_TOURDULICH;Integrated S" +
            "ecurity=True")]
        public string QL_TOURDULICHConnectionString6 {
            get {
                return ((string)(this["QL_TOURDULICHConnectionString6"]));
            }
        }
    }
}
