CREATE DATABASE DB_QLSHOPMYPHAM

GO
USE DB_QLSHOPMYPHAM

GO
CREATE TABLE LOAI
(
	MALOAI VARCHAR(50) NOT NULL,
	TENLOAI NVARCHAR(100),
	NOINHAPKHAU NVARCHAR(200),
	CONSTRAINT PK_MALOAI PRIMARY KEY(MALOAI)
)

GO
CREATE TABLE NHASANXUAT
(
	MANSX VARCHAR(50) NOT NULL,
	TENNSX NVARCHAR(100),
	DIACHI NVARCHAR(200),
	THOIGIANTHANHLAP DATE,
	IMG_LOGO VARCHAR(200),
	CONSTRAINT PK_MANSX PRIMARY KEY(MANSX)
)

GO
CREATE TABLE SANPHAM
(
	MASP VARCHAR(50) NOT NULL,
	TENSP NVARCHAR(100),
	MOTA NVARCHAR(1000),
	GIA MONEY,
	SOLUONG INT,
	MALOAI VARCHAR(50),
	MANSX VARCHAR(50),
	IMG_SP VARCHAR(200),
	CONSTRAINT PK_MASP PRIMARY KEY(MASP)
)


GO
ALTER TABLE SANPHAM
ADD DS_HINH VARCHAR(200)

ALTER TABLE SANPHAM
ADD CONSTRAINT FK_SP_MALOAI FOREIGN KEY(MALOAI) REFERENCES LOAI(MALOAI)

ALTER TABLE SANPHAM
ADD CONSTRAINT FK_SP_MANSX FOREIGN KEY(MANSX) REFERENCES NHASANXUAT(MANSX)


GO
CREATE TABLE KHACHHANG
(
	MAKH VARCHAR(50) NOT NULL,
	TENKH NVARCHAR(100),
	NGAYSINH DATE,
	GIOITINH NVARCHAR(50),
	DS_MASP_DAMUA VARCHAR(1000),
	LOAIKH NVARCHAR(50) DEFAULT(N'Thông thường'),
	SDT VARCHAR(50),
	EMAIL VARCHAR(100),
	DIACHI NVARCHAR(200),
	MATAIKHOAN_LOGIN VARCHAR(50),
	IMG_KH VARCHAR(200),
	MATKHAU VARCHAR(50) NOT NULL,
	CONSTRAINT PK_MAKH PRIMARY KEY(MAKH)
)


GO
CREATE TABLE DONHANG
(
	MADH INT IDENTITY NOT NULL,
	MASP_DATMUA VARCHAR(50) NOT NULL,
	SOLUONG INT,
	GIA FLOAT,
	NGAYDATMUA DATE,
	NGAYGIAOHANG DATE,
	MAKH VARCHAR(50),
	CONSTRAINT PK_MADH PRIMARY KEY(MADH, MASP_DATMUA)
)

GO
ALTER TABLE DONHANG
ADD CONSTRAINT FK_DH_MASP FOREIGN KEY(MASP_DATMUA) REFERENCES SANPHAM(MASP)

ALTER TABLE DONHANG
ADD CONSTRAINT FK_DH_MAKH FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH)


GO
CREATE TABLE NHANVIEN
(
	MANV VARCHAR(50) NOT NULL,
	TENNV NVARCHAR(100),
	NGAYSINH DATE,
	GIOITINH NVARCHAR(50),
	LOAINV NVARCHAR(50) DEFAULT(N'Bán hàng'),
	SDT VARCHAR(50),
	EMAIL VARCHAR(100),
	DIACHI NVARCHAR(200),
	MATAIKHOAN_LOGIN VARCHAR(50),
	IMG_NV VARCHAR(200),
	MATKHAU_NV VARCHAR(50) NOT NULL,
	CONSTRAINT PK_MANV PRIMARY KEY(MANV)
)





-------------------------------------INSERT INTO--------------------------


SET DATEFORMAT DMY
INSERT INTO NHASANXUAT
VALUES('N001',N'HOÀNG NHÂN',N'HỒ CHÍ MINH','01/08/2016','HoangNhan.jpg'),
	('N002',N'HANOCOS',N'VŨNG TÀU','15/10/2008','Hanacos.jpg'),
	('N003',N'VIMAC',N'CÀ MAU','28/03/2001','Vimac.jpg'),
	('N010','DIOR','FRANCE','01/12/1996','dior.jpg'),
	('N011','CHANEL','EU','04/2/1999','chanel.jpg'),
	('N012','ACNES','UK','3/4/1989','ACNES.jpg'),
	('N013','AQUA FRESH','KOREA','2/2/2001','AQUA FRESH.jpg'),
	('N014','ANESSA','FRANCE','14/12/1995','ANESSA.jpg'),
	('N015','AU FAIRY','SINGAPORE','4/11/2000','AU FAIRY.jpg'),
	('N016','AURA BEAUTY','VN','5/6/1998','AURA BEAUTY.jpg'),
	('N017','AUSTRALIS','US','23/7/1990','AUSTRALIS.jpg'),
	('N018','AVANDER','CHINA','18/2/1998','AVANDER.jpg'),
	('N019','AVATAR','EU','04/2/1999','AVATAR.jpg')

GO
INSERT INTO LOAI
VALUES('L001',N'SON MÔI',N'VIỆT NAM'),
	('L002',N'KEM DƯỠNG DA',N'HÀN QUỐC'),
	('L003',N'THUỐC NHUỘM TÓC',N'MỸ'),
	('L010',N'NƯỚC HOA','EU'),
	('L011',N'KEM NỀN','ANH'),
	('L012',N'KEM LÓT','FRACE'),
	('L013',N'PHẤN PHỦ','US'),
	('L014',N'PHẤN NƯỚC','CHINA'),
	('L015',N'TẠO KHỐI ','UK'),
	('L016',N'CHE KHUYẾT ĐIỂM','KOREA'),
	('L017',N'SON DƯỠNG ','FRANCE'),
	('L018',N'SON LÌ','UK'),
	('L019',N'SON BÓNG','UK')

GO
INSERT INTO SANPHAM
VALUES ('SP001',N'Mặt Nạ Đường Đen Dâu Skinfood',N'Với công nghệ sản xuất bông tiên tiến, bông tẩy trang IPEK giúp tẩy trang và làm sạch mọi bụi bẩn bám trên da. Miếng bông được dệt thành 2 mặt khác nhau giúp tận dụng được tối đa sản phẩm. Sợi bông mềm mịn thấm hút sâu dung dịch, nhẹ nhàng tẩy sạch vùng da nhạy cảm quanh mắt. Tẩy sạch sâu làn da mà tuyệt đối không để lại xơ, cho làn da sáng mịn, rạng ngời.',190000, 100,'L001','N001','SP1.jpg','h1.jpg;h2.jpg;h3.jpg'),
	('SP002',N'Son Kem Bourjois Rouge Edition Velvet',N'Với công nghệ sản xuất bông tiên tiến, bông tẩy trang IPEK giúp tẩy trang và làm sạch mọi bụi bẩn bám trên da. Miếng bông được dệt thành 2 mặt khác nhau giúp tận dụng được tối đa sản phẩm. Sợi bông mềm mịn thấm hút sâu dung dịch, nhẹ nhàng tẩy sạch vùng da nhạy cảm quanh mắt. Tẩy sạch sâu làn da mà tuyệt đối không để lại xơ, cho làn da sáng mịn, rạng ngời.',5850000, 200,'L001','N002','SP2.jpg','h4.jpg;h5.jpg;h6.jpg'),
	('SP003',N'Thuốc Nhuộm Tóc 7 Màu Hàn Quốc',N'Với công nghệ sản xuất bông tiên tiến, bông tẩy trang IPEK giúp tẩy trang và làm sạch mọi bụi bẩn bám trên da. Miếng bông được dệt thành 2 mặt khác nhau giúp tận dụng được tối đa sản phẩm. Sợi bông mềm mịn thấm hút sâu dung dịch, nhẹ nhàng tẩy sạch vùng da nhạy cảm quanh mắt. Tẩy sạch sâu làn da mà tuyệt đối không để lại xơ, cho làn da sáng mịn, rạng ngời.',1000000, 500,'L002','N003','SP3.jpg','h7.jpg;h8.jpg;h9.jpg'),
	('SP004',N'Thuốc nhuộm tóc Double Rich Trend Color 6B',N'Với công nghệ sản xuất bông tiên tiến, bông tẩy trang IPEK giúp tẩy trang và làm sạch mọi bụi bẩn bám trên da. Miếng bông được dệt thành 2 mặt khác nhau giúp tận dụng được tối đa sản phẩm. Sợi bông mềm mịn thấm hút sâu dung dịch, nhẹ nhàng tẩy sạch vùng da nhạy cảm quanh mắt. Tẩy sạch sâu làn da mà tuyệt đối không để lại xơ, cho làn da sáng mịn, rạng ngời.',70000, 1000,'L003','N001','SP4.jpg','h10.jpg;h11.jpg;h12.jpg'),
	('SP005',N'Kem Body Dưỡng Trắng Phân Tử Nước',N'Với công nghệ sản xuất bông tiên tiến, bông tẩy trang IPEK giúp tẩy trang và làm sạch mọi bụi bẩn bám trên da. Miếng bông được dệt thành 2 mặt khác nhau giúp tận dụng được tối đa sản phẩm. Sợi bông mềm mịn thấm hút sâu dung dịch, nhẹ nhàng tẩy sạch vùng da nhạy cảm quanh mắt. Tẩy sạch sâu làn da mà tuyệt đối không để lại xơ, cho làn da sáng mịn, rạng ngời.',220000, 80,'L001','N003','SP5.jpg','h13.jpg;h14.jpg;h15.jpg'),
	('SP006',N'Son Bóng Dưỡng Môi Pha Lê',N'Với công nghệ sản xuất bông tiên tiến, bông tẩy trang IPEK giúp tẩy trang và làm sạch mọi bụi bẩn bám trên da. Miếng bông được dệt thành 2 mặt khác nhau giúp tận dụng được tối đa sản phẩm. Sợi bông mềm mịn thấm hút sâu dung dịch, nhẹ nhàng tẩy sạch vùng da nhạy cảm quanh mắt. Tẩy sạch sâu làn da mà tuyệt đối không để lại xơ, cho làn da sáng mịn, rạng ngời.',370000, 120,'L003','N002','SP6.jpg','h16.jpg;h17.jpg;h18.jpg'),
----------------------------------LOẠI 1 : NƯỚC HOA ------------------------------------
	('SP010',N'CHRISTIAN DIOR Sauvage Parfum',N'Mùi hương của phố thị hiện đại ồn ào. Phảng phất đâu đó mùi Cocktail Mojito mát lạnh cùng lớp gỗ mỏng manh, đậm mùi vỏ cam chanh tươi mát',2890000 ,20,'L010','N010','SP10.JPG','10_1.jpg;10_2.jpg;10_3.jpg;10_4.jpg'),
	('SP011',N'CHRISTIAN DIOR Sauvage EDP',N'Đại diện thương hiệu cho sản phẩm lần này là nam diễn viên điện ảnh nổi tiếng Johnny Deepp với tạo hình thời trang cho hình ảnh nước hoa mới với mái tóc dài rủ phong trần, nam tính bụi bặm với sơ mi phanh ngực, và phụ kiện ấn tượng,  tattoo cực ngầu để phù hợp với một Sauvage hoang dã đích thực !', 2690000,20,'L010','N010','SP11.JPG','11_1.jpg;11_2.jpg;11_3.jpg;11_4.jpg'),
	('SP012',N'CHRISTIAN DIOR Sauvage EDT',N'Hương thơm hoàn toàn mới mẻ với những sắc thái trái ngược nhưng bổ sung cho nhau một cách hoàn hảo với vị tươi, thô, với các thành phần tự nhiên được lựa chọn cẩn thận. Ấn tượng từ khi mở màn tới kết thúc với hổ phách thơm nức mũi hòa quyện cùng cam quýt tươi mát và xạ hương ngọt ấm áp', 2390000,30,'L010','N010','SP12.JPG','12_1.jpg;12_2.jpg;12_3.jpg;12_4.jpg'),
	('SP013',N'CHRISTIAN DIOR Homme Sport',N'Ngoài cái sự bùng nổ, sảng khoái như các dòng nước hoa Sport khác, thì DIOR có vị đắng rất đặc biệt, vừa tôn lên chất mạnh mẽ vừa như dùng mùi khắc nên nét ký của nhà D.ior. Note trái cây khoẻ khoắn nam tính và cứng rắn', 2490000,10,'L010','N010','SP13.JPG','13_1.jpg;13_2.jpg;13_3.jpg;13_4.jpg'),
	('SP014',N'CHRISTIAN DIOR Homme Intense',N'Dior Homme Intense eau de Parfum tỏa ra ngây ngất bằng sự hòa quyện vô cùng tinh tế giữa các nhóm hương Gỗ – Hoa – Xạ hương, giúp mùi thơm lưu lại trên da thật lâu, thật đậm, thật ngọt ngào mà cũng vô cùng sâu lắng. Là một trong những dòng hương Eau de Parfum vô cùng đặc biệt và hiếm có dành cho nam giới. Có lẽ vì thế Dior Homme Intense eau de Parfum được đánh giá là một trong những mùi hương được săn đón nhất trên thế giới!', 2490000,50,'L010','N010','SP14.JPG','14_1.jpg;14_2.jpg;14_3.jpg;14_4.jpg'),
	('SP015',N'CHRISTIAN DIOR Homme',N'Hương đậm đà của gỗ chính là yếu tố chủ đạo tạo nên sự cuốn hút trong Dior Homme 2020. Cảm giác ấm áp từ Gỗ Cashmere, vị cay nhẹ của Gỗ tuyết tùng, đan xen Hoắc hương và Hồng tiêu. Dior Homme kết hợp đầy ngẫu hứng nhưng tạo nên phong cách quyến rũ, sâu lắng khó quên', 2390000,20,'L010','N010','SP15.JPG','15_1.jpg;15_2.jpg;15_3.jpg;15_4.jpg'),
	('SP016',N'CHANEL Bleu De Chanel Parfum',N'Bleu De Chanel Parfum ấn tượng từ lần xịt đầu tiên với hương thơm ngát trong veo từ vỏ chanh vàng, cam bergamot và bạc hà mát lạnh. Ở lớp hương giữa cho ta cảm nhận vị ngọt ngào từ hoa trái đến tận phút cuối cùng khi oải hương yếu dần và chìm vào quên lãng thì lúc này, vị gỗ tuyết tùng, đàn hương nồng nàn và hổ phách đầy đặn ùa về vô cùng mạnh mẽ, ấm áp và sâu lắng', 3590000,20,'L010','N011','SP16.JPG','16_1.jpg;16_2.jpg;16_3.jpg;16_4.jpg'),
	('SP017',N'CHANEL Allure Homme Edition Blanche',N'Lấy cảm hứng từ phương Đông hiện đại, mùi hương mang tính sáng tạo và độc đáo. Vừa gợi cảm tinh tế nhẹ nhàng và quý phái. Hương thơm là cả một nghệ thuật của sự tinh tuý',3890000,20,'L010','N011','SP17.JPG','17_1.jpg;17_2.jpg;17_3.jpg;17_4.jpg'),
	('SP018',N'CHANEL Allure Homme Sport Eau Extreme',N'Ra đời năm 2014, Nước hoa CHANEL Allure Homme Sport Eau Extreme for men nằm trong chuỗi nước hoa Allure Homme huyền thoại. Phiên bản Sport Eau Extreme chính là đứa con cưng của Jacques Polge dành cho những quý ông năng động. Đây sự kết hợp giữa thành phần hoa cỏ thiên nhiên, gỗ thơm sâu lắng cũng một chút cay nồng. Nước hoa mang đến cho phái mạnh sự tự tin trong mọi hoạt động trong ngày.', 3390000,20,'L010','N011','SP18.JPG','18_1.jpg;18_2.jpg;18_3.jpg;18_4.jpg'),
	('SP019',N'CHANEL Bleu De Chanel Eau De Parfum',N'de Chanel Pour Homme Eau De Parfum là phiên bản nâng cấp của Bleu de Chanel huyền thoại 2010. Phiên bản mới ra đời năm 2014 cũng bởi bàn tay ma thuật của Jacques Polge, 4 năm sau phiên bản gốc. Sản phẩm lần này tiếp tục là một sự hòa quyện đầy màu sắc và hứng khởi của Channel', 9890000,20,'L010','N011','SP19.JPG','19_1.jpg;19_2.jpg;19_3.jpg;19_4.jpg'),
----------------------------------LOẠI 2 : KEM NỀN -----------------------------------
	('SP020',N'Kem Nền Maybelline Mịn Nhẹ Kiềm Dầu Chống Nắng 30ml Fit',N'Kem Nền Maybelline Mịn Nhẹ Kiềm Dầu Chống Nắng Matte Poreless Foundation SPF 22 30ml là kem nền đến từ thương hiệu mỹ phẩm MAYBELLINE của Mỹ, với công nghệ Micro Powders hạt phấn siêu nhỏ không dầu, không hương liệu độc quyền cho hiệu ứng mịn lì tự nhiên, tiệp màu da cùng khả năng kiềm dầu hiệu quả cả ngày dài, phù hợp cho da dầu.',155000,300,'L011','N011','SP20.jpg','20_1.JPG;20_2.JPG;20_3.JPG;20_4.JPG'),
	('SP021',N'Kem Nền Klairs Trang Điểm Giúp Lớp Nền Căng Mịn 40ml Illuminating Supple Blemish Cream SPF40/PA++','Kem Nền Trang Điểm Illuminating Supple Blemish Cream SPF40/PA++ đến từ thương hiệu mỹ phẩm Klairs hứa hẹn sẽ đám ứng mọi tiêu chí của bạn với khả năng che phủ tốt, đảm nhiệm mọi chức năng của kem chống nắng, kem lót, phấn phủ chỉ trong một sản phẩm. Cùng thành phần lành tính, phù hợp mọi tông da mang đến cho bạn làn da căng bóng, tự nhiên như không trang điểm.',242000,400,'L011','N011','SP21','21_1.JPG;21_2.JPG;21_3.JPG;21_4.JPG'),
	('SP022',N'Kem Nền Estee Lauder Lâu Trôi 3W0 Warm Crème 30ml (HSD 12/2021)','Double Wear Stay-in-Place Makeup là một trong những dòng sản phẩm bán chạy nhất của thương hiệu mỹ phẩm cao cấp đến từ Pháp - Estée Lauder. Sản phẩm nổi tiếng về độ che phủ cũng như độ bám màu và nhận được đánh giá rất tốt từ khách hàng và các blogger và youtuber chuyên review về mỹ phẩm. Double Wear Stay-in-Place Makeup phù hợp với mọi loại da, đặc biệt là da hỗn hợp và da dầu.',362000,10,'L011','N010','SP22','22_1.JPG;22_2.JPG;22_3.JPG;22_4.JPG'),
	('SP023',N'Kem Nền Shu Uemura Giàu Dưỡng Chất 764 - 35ml Unlimited Glow Fluid Foundation SPF18 PA+++','Kem Nền Shu Uemura Unlimited Glow Fluid Foundation SPF18 PA+++ là dòng sản phẩm trang điểm nền cao cấp mới ra mắt từ thương hiệu Shu Uemura, được lấy cảm hứng từ quá trình chăm sóc da, giúp mang đến một công thức kem nền dạng lỏng giàu dưỡng chất, cho hiệu ứng che phủ cao đồng thời mang lại cho làn da cảm giác ẩm mượt suốt cả ngày dài. Sản phẩm đặc biệt phù hợp cho tông da của phụ nữ châu Á.',990000 ,10,'L011','N003','SP23','23_1.JPG;23_2.JPG;23_3.JPG;23_4.JPG'),
	('SP024',N'Kem Nền CC Cathy Doll Màu Sáng 01 Light Beige 50g Speed White CC Cream SPF50+/PA+++','Kem Nền CC Cathy Doll Trang Điểm Và Dưỡng Sáng Speed White CC Cream SPF50+/PA+++ là dòng kem nền trang điểm đến từ thương hiệu mỹ phẩm Cathy Doll của Thái Lan, với 5 công dụng trong 1: Kem dưỡng sáng - Kem chống nắng - Kem lót - Kem nền - Phấn phủ sẽ giúp quá trình trang điểm vào buổi sáng của nhanh - gọn - lẹ hơn bao giờ hết mà bạn vẫn sở hữu gương mặt không tì vết.',150000,100,'L011','N010','SP24','24_1.JPG;24_2.JPG;24_3.JPG;24_4.JPG'),
	('SP025',N'Kem Nền Kem Nền Lâu Trôi L’Oreal Paris SPF16 105 Natural Beige 30ml Infallible 24H Matte Cover','Kem Nền Lâu Trôi L’Oreal Paris Infallible 24H Matte Cover SPF16 là dòng sản phẩm kem nền mới ra mắt năm 2020 từ L’Oreal Paris - tập đoàn chuyên về mỹ phẩm và chăm sóc sắc đẹp hàng đầu thế giới, có khả năng kiềm dầu tốt và bền màu lâu trôi lên đến 24 giờ, cho hiệu ứng lớp nền mịn lì tự nhiên, không bết dính, đồng thời bảo vệ da trước tia UVA/UVB với chỉ số chống nắng SPF16 PA+++.',193000,400,'L011','N012','SP25','25_1.JPG;25_2.JPG;25_3.JPG;25_4.JPG'),
	('SP026',N'Kem Nền Che Phủ Cao Flormar Light Beige 30ml Invisible Cover HD Foundation','Kem Nền Che Phủ Cao Flormar Invisible Cover HD Foundation từ thương hiệu Flormar của Ý mang đến cho bạn lớp nền mịn mướt, che khuyết điểm cực tốt mà lại mỏng nhẹ, không hề bí da. Đây chính là lựa chọn thích hợp với những cô nàng da dầu, mang đến cho bạn lớp nền mịn mượt, khô thoáng và che phủ “hoàn hảo” đến từng lỗ chân lông',349000,50,'L011','N012','SP26','26_1.JPG;26_2.JPG;26_3.JPG;26_4.JPG'),
	('SP027',N'Kem Nền Anessa Trang Điểm Chống Nắng Dạng Nén Natural 10g Perfect UV','Kem Nền Trang Điểm Chống Nắng Dạng Nén Anessa Perfect UV Sunscreen Skincare Makeup Base SPF50+ PA+++ đến từ thương hiệu chống nắng Anessa thuộc tập đoàn Shiseido Nhật Bản, với thiết kế dạng nén nhỏ gọn kèm bông mút, cùng chỉ số SPF50+ PA+++ cho khả năng chống UV vượt trội và độ che phủ đồng đều bề mặt da, tạo lớp nền mịn mượt suốt ngày dài, duy trì làn da đẹp rạng rỡ. Thích hợp sử dụng hàng ngày và các hoạt động ngoài trời.',598000,100,'L011','N011','SP27','27_1.JPG;27_2.JPG;27_3.JPG;27_4.JPG'),
	('SP028',N'Kem Nền Australis Bắt Sáng Che Phủ Cao Tông Da 28ml Oh 2 Glow Light Diffusing Foundation ','Nếu bạn là người yêu thích phong cách trang điểm nền căng mịn bóng khỏe, tạo cảm giác trong trẻo và “tự nhiên như không trang điểm”, chắc chắn bạn không thể bỏ qua Kem Nền Bắt Sáng Che Phủ Cao Australis Oh 2 Glow Light Diffusing Foundation đến từ thương hiệu mỹ phẩm trang điểm nổi tiếng Australis. Đây là dòng kem nền rất được yêu thích bởi cộng đồng làm đẹp và đã được nhận giải thưởng Best in Beauty Award 2017 của tạp chí Beauty Heaven tại Úc.  bảo vệ làn da khỏi các tổn thương do gốc tự do gây ra, từ đó ngăn ngừa lão hóa da.',342000,400,'L011','N013','SP28','28_1.JPG;28_2.JPG;28_3.JPG;28_4.JPG'),
	('SP029',N'Kem Nền Clinique Làm Sáng Da 64 Cream Beige 30ml (HSD 12/2021)','Khi các cô gái luôn muốn xuất hiện với một vẻ bề ngoài xinh đẹp cùng làn da được trang điểm nhẹ nhàng, tươi tắn thì việc sử dụng kem nền trong trang điểm càng trở nên quan trọng. Để có được một làn da vừa mịn màng không tì vết, vừa giữ được sự tự nhiên, mỏng mịn, không bị dày phấn, không mốc thì trước tiên bạn cần chọn đúng loại kem nền phù hợp với làn da của mình. Kem Nền Giúp Làm Sáng Da Clinique Even Better Glow Light Reflecting Makeup với thành phần chứa các hạt kháng chất tự nhiên cùng chất kem mềm mượt, dễ tán đều sẽ giúp bạn có một lớp nền trang điểm đẹp, lì và hạn chế tình trạng xuống tông sau khi một thời gian trang điểm. Ngoài ra, chỉ số chống nắng SPF15 còn giúp hỗ trợ bảo vệ da trước tác động của ánh nắng mặt trời. Kem không .',291000,400,'L011','N001','SP29','29_1.JPG;29_2.JPG;29_3.JPG;29_4.JPG'),
----------------------------------LOẠI 3: KEM LÓT ------------------------------------
	('SP030',N'Blemish Buster Acne Fighting Primer',N'Một trong những bí quyết để có được lớp nền hoàn hảo và bền màu lâu trôi suốt nhiều giờ chính là sử dụng kem lót trang điểm (primer). Kem lót được sử dụng trước khi makeup, giúp lấp đầy những khuyết điểm trên da như lỗ chân lông to, sẹo mụn, làm cho bề mặt da bằng phẳng mịn màng và “ăn phấn” hơn', 7540000,20,'L012','N011','SP30.JPG','30_1.jpg;30_2.jpg;30_3.jpg;30_4.jpg'),
	('SP031',N'Baby Skin Pore Eraser',N'Sử dụng kem lót khi trang điểm là một bước không thể thiếu để sở hữu gương mặt đẹp hoàn hảo. Kem Lót Trang Điểm Maybelline Baby Skin Instant Pore Eraser 22ml chắc chắn sẽ là phương pháp cứu nguy cho lớp nền của bạn. Mau trôi, nhanh xuống tông, lộ khuyết điểm: mụn đỏ và lỗ chân lông to chỉ cò là chuyện nhỏ nếu bạn sử dụng em kem lót trang điểm kiềm dầu Maybelline Baby Skin Instant Pore Eraser này!', 2340000,60,'L012','N011','SP31.JPG','31_1.jpg;31_2.jpg;31_3.jpg;31_4.jpg'),
	('SP032',N'Eyeshadow Primer',N'Nhiều cô nàng sẵn sàng chi trả rất nhiều tiền cho các sản phẩm phấn nền, phấn lót, phấn phủ, son môi… nhưng lại đắn đo không mua kem lót mắt. Thực tế, đây là bước quan trọng không nên bỏ qua nếu như bạn muốn “họa” được một đôi mắt đẹp, sâu hút hồn và bền màu suốt cả ngày dài. Cũng như da mặt, kem lót mắt (Eye Primer) sẽ giúp tạo một lớp nền cho mí mắt và vùng bầu mắt, hấp thụ đi lượng dầu thừa đối với những bạn có da mắt nhiều dầu và giúp che đi các khuyết điểm như các nếp gấp nhỏ, nếp nhăn', 5250000,30,'L012','N010','SP32.JPG','32_1.jpg;32_2.jpg;32_3.jpg;32_4.jpg'),
	('SP033',N'Make Up Base',N'Chìa khóa cho một lớp nền hoàn hảo đương nhiên không thể thiếu chính là kem lót (make-up base). Kem lót là bước đầu tiên trong quy trình make-up, giúp tạo lớp lót mịn màng, hỗ trợ làm cho kết cấu da trở nên đồng nhất, che phủ lỗ chân lông to, từ đó giúp các bước trang điểm tiếp theo được mượt mà hơn, da “ăn phấn” hơn. Ngoài ra kem lót còn có công dụng dưỡng ẩm hoặc kiềm dầu cho da, giúp giữ lớp nền được bền màu lâu trôi suốt cả ngày dài, hạn chế tình trạng da khô mốc cakey hoặc da tiết dầu làm oxy hóa xuống tông nền.', 7640000,60,'L012','N012','SP33.JPG','33_1.jpg;33_2.jpg;33_3.jpg;33_4.jpg'),
	('SP034',N'The Original Primer',N'Một trong những bí quyết để có được lớp nền hoàn hảo và bền màu lâu trôi suốt nhiều giờ chính là sử dụng kem lót trang điểm (primer). Kem lót được sử dụng trước khi makeup, giúp lấp đầy những khuyết điểm trên da như lỗ chân lông to, sẹo mụn, làm cho bề mặt da bằng phẳng mịn màng và “ăn phấn” hơn, đồng thời còn có thêm một số công dụng khác như kiềm dầu, giữ lớp nền lâu trôi, giảm hiện tượng nền loang lổ vào cuối ngày, dưỡng ẩm cho da ẩm mượt và không bị cakey hay bong tróc nền', 8570000,20,'L012','N017','SP34.JPG','34_1.jpg;34_2.jpg;34_3.jpg;34_4.jpg'),
	('SP035',N'Mattifying Makeup Primer',N'Một trong những quan điểm sai lầm nhất khi trang điểm chính là bỏ qua bước kem lót, khiến cho lớp nền mau trôi, dễ bị bóng dầu, xỉn màu và xuống tông nhanh chóng. Kem lót tưởng chừng như không quan trọng nhưng lại là nhân tố to lớn góp phần giúp bạn có được một lớp nền mịn đẹp hoàn hảo, bền màu và lâu trôi. Kem lót có khả năng lấp đầy những khuyết điểm trên da như lỗ chân lông to, sẹo mụn, làm cho bề mặt da bằng phẳng mịn màng và “ăn phấn” hơn, đồng thời còn có thêm một số công dụng khác như kiềm dầu, giữ lớp nền lâu trôi, giảm hiện tượng nền loang lổ vào cuối ngày… Ngoài ra, kem lót còn hoạt động như một lớp màng chắn giữa làn da và các sản phẩm trang điểm, giúp bảo vệ da không bị tổn hại bởi hóa chất trong mỹ phẩm makeup nữa đấy.', 3450000,60,'L012','N018','SP35.JPG','35_1.jpg;35_2.jpg;35_3.jpg;35_4.jpg'),
	('SP036',N'Primer The Original',N'Một trong những bí quyết để có được lớp nền hoàn hảo và bền màu lâu trôi suốt nhiều giờ chính là sử dụng kem lót trang điểm (primer). Kem lót được sử dụng trước khi makeup, giúp lấp đầy những khuyết điểm trên da như lỗ chân lông to, sẹo mụn, làm cho bề mặt da bằng phẳng mịn màng và “ăn phấn” hơn, đồng thời còn có thêm một số công dụng khác như kiềm dầu, giữ lớp nền lâu trôi, giảm hiện tượng nền loang lổ vào cuối ngày, dưỡng ẩm cho da ẩm mượt và không bị cakey hay bong tróc nền', 2670000,70,'L012','N014','SP36.JPG','36_1.jpg;36_2.jpg;36_3.jpg;36_4.jpg'),
	('SP037',N'Cya Later Pores Spot Primer',N'Một trong những bí quyết để có được lớp nền hoàn hảo và bền màu lâu trôi suốt nhiều giờ chính là sử dụng kem lót trang điểm (primer). Kem lót được sử dụng trước khi makeup, giúp lấp đầy những khuyết điểm trên da như lỗ chân lông to, sẹo mụn, làm cho bề mặt da bằng phẳng mịn màng và “ăn phấn” hơn, đồng thời còn có thêm một số công dụng khác như kiềm dầu, giữ lớp nền lâu trôi, giảm hiện tượng nền loang lổ vào cuối ngày… Đặc biệt đối với làn da dầu và lỗ chân lông to thì kem lót là rất cần thiết vì không những làm cho lớp nền mịn đẹp mà còn ngăn tình trạng da bóng dầu làm trôi makeup.', 2660000,80,'L012','N019','SP37.JPG','37_1.jpg;37_2.jpg;37_3.jpg;37_4.jpg'),
	('SP038',N'Colour Clique CC Primer - Pink Lady',N'(makeup base) là một trong những bước quan trọng để có được một lớp nền mịn đẹp hoàn hảo và bền màu lâu trôi suốt cả ngày dài. Kem lót được sử dụng ở bước đầu tiên trước khi bắt đầu các bước trang điểm nền (Cushion/BB Cream/CC Cream/Foundation), giúp hiệu chỉnh tông màu da, làm đồng đều sắc da, hỗ trợ che phủ các khuyết điểm như mụn/thâm mụn/đốm nâu/quầng thâm/mạch máu nổi rõ…, chuẩn bị cho lớp nền phía sau được mịn màng, tăng độ bám dính nền và có độ che phủ tối ưu nhất. Ngoài ra, kem lót cũng có chức năng kiềm dầu, điều tiết lượng bã nhờn dư thừa cho da được thông thoáng nhẹ nhàng, hạn chế việc da đổ dầu làm lớp nền bị oxi hóa, xỉn màu và xuống tông, giữ cho lớp nền lâu trôi hơn. Không chỉ thế, kem lót còn là một “lớp khiên” ngăn cách giữa làn da và các sản phẩm trang điểm, góp phần bảo vệ da khỏi bị tổn thương.', 7430000,30,'L012','N011','SP38.JPG','38_1.jpg;38_2.jpg;38_3.jpg;38_4.jpg'),
	('SP039',N'Instant Pore Fix Primer',N'Kem Lót Che Lỗ Chân Lông SILKYGIRL Instant Pore Fix Primer Màu 01 Natural 15ml là kem lót đến từ thương hiệu mỹ phẩm SILKYGIRL từ Malaysia, chất kem mỏng nhẹ giúp hỗ trợ làm mờ và thu nhỏ lỗ chân lông hiệu quả, giữ lớp makeup lâu trôi cả ngày dài, đồng thời che khuyết điểm, không gây bết dính. Hiện sản phẩm Kem Lót Che Lỗ Chân Lông SILKYGIRL Instant Pore Fix Primer Màu 01 Natural 15ml đã có mặt', 2860000,10,'L012','N016','SP39.JPG','39_1.jpg;39_2.jpg;39_3.jpg;39_4.jpg'),
----------------------------------LOẠI 4: PHẤN PHỦ ----------------------------------
	('SP040',N'Fit Me Matte + Poreless Powder',N'Da dầu có lẽ là làn da gặp nhiều vấn đề và khó chiều đối với chị em phụ nữ chúng ta. Da dầu tuy làm chậm quá trình lão hóa của da, khiến da bạn trẻ trung và đàn hồi hơn, tuy nhiên khuyết điểm lớn nhất chính là phần dầu thừa không cần thiết khiến da bạn bóng dầu, dễ bắt bụi bẩn, và cũng là nguyên nhân chính gây ra mụn. Và một trong những giải pháp đơn giản nhất để khắc phục tình trạng này chính là dùng phấn phủ.', 2330000,20,'L013','N012','SP40.JPG','40_1.jpg;40_2.jpg;40_3.jpg;40_4.jpg'),
	('SP041',N'Shine-free Loose Powder',N'là phấn phủ dạng bột đến từ thương hiệu SILKYGIRL, với kết cấu hạt phấn mỏng, nhẹ, tạo cảm giác thông thoáng và không gây bí bách, giúp mang lại lớp trang điểm nhẹ nhàng và vô cùng tự nhiên, cùng với công thức không chứa dầu và khả năng điều tiết bóng nhờn tốt, giữ cho làn da của bạn luôn tươi tắn suốt cả ngày. Sản phẩm dùng cho mọi loại da, phù hợp cho những người mới bắt đầu trang điểm.', 2350000,40,'L013','N013','SP41.JPG','41_1.jpg;41_2.jpg;41_3.jpg;41_4.jpg'),
	('SP042',N'Pearl Pact',N'là dòng phấn phủ đến từ thương hiệu mỹ phẩm Essance của Hàn Quốc, chứa thành phần ngọc trai với hạt phấn ánh hồng, bắt sáng nhẹ nhàng cho gương mặt hồng hào, tươi sáng rạng rỡ.', 2560000,20,'L013','N014','SP42.JPG','42_1.jpg;42_2.jpg;42_3.jpg;42_4.jpg'),
	('SP043',N'Glow Powder Pact Pitch Pink',N'Trang điểm sẽ giúp cho các cô nàng trở nên xinh đẹp và đáng yêu hơn. Thế nhưng đa số các nàng vẫn thường băn khoăn lo lắng về việc thường xuyên trang điểm có làm cho làn da trở nên bị xấu xí và tổn hại hay không? Tuy nhiên giờ đây các nàng hoàn toàn có thể yên tâm khi đến với Phấn Phủ Có Nhũ Eglips Glow Powder Pact Pitch Pink bởi đây là phấn phủ dạng nén tự nhiên chứa bột ngọc trai, cho lớp phấn ánh hồng, khiến da trông hồng hào khỏe khoắn, kiểm soát lớp dầu thừa trên da một cách hiệu quả, che phủ lỗ chân lông giúp da nhìn khỏe khoắn tự nhiên. Phấn phủ chứa chiết xuất hoa oải hương', 9470000,80,'L013','N012','SP43.JPG','43_1.jpg;43_2.jpg;43_3.jpg;43_4.jpg'),
	('SP044',N'Pressed Powder #Deep Natural',N'Sau khi apply kem nền, đặc biệt là với các sản phẩm kem nền dạng lỏng thì phấn phủ là bước không thể thiếu để cố định lại lớp trang điểm, tạo hiệu ứng lớp nền mịn lì và khô thoáng, giữ cho lớp nền luôn bền màu và lâu trôi suốt cả ngày dài, tránh hiện tượng da đổ dầu dẫn đến oxy hóa làm cho lớp nền bị xuống tông, loang lổ kém thẩm mỹ', 9370000,90,'L013','N016','SP44.JPG','44_1.jpg;44_2.jpg;44_3.jpg;44_4.jpg'),
	('SP045',N'Pure Smooth Pressed Powder',N'Phấn phủ là bước cuối cùng không thể thiếu với một lớp nền đẹp, giúp lớp trang điểm được cố định, lâu trôi sau nhiều giờ. Phấn phủ còn được xem là biện pháp bảo vệ da khỏi tác hại của ánh nắng mặt trời hay các tác nhân gây hại từ bên ngoài. SILKYGIRL Pure Smooth Pressed Powder SPF20 là phấn phủ trang điểm mịn da giúp che phủ mọi khuyết điểm trên làn da bạn mà không hề gây khô da. Mang đến làn da mịn màng, rạng rỡ đầy tự nhiên đấy nhé!', 3460000,60,'L013','N018','SP45.JPG','45_1.jpg;45_2.jpg;45_3.jpg;45_4.jpg'),
	('SP046',N'Blur Powder Pact',N'Phấn phủ đối với những cô nàng hay trang điểm chiếm vị trí khá quan trọng trong quy trình makeup. Phấn phủ được dùng ở công đoạn cuối cùng sau khi các bạn đã hoàn thành xong tất cả các lớp kem và phấn trước đó, và là sản phẩm có rất nhiều tính năng cần thiết góp phần giúp mang lại cho bạn làn da láng mịn, và là “bức tường” bảo vệ da trước sự xâm nhập của vi khuẩn, bụi bẩn. Phấn Phủ Siêu Mịn Eglips Blur Powder Pact có kết cấu dịu nhẹ gồm hàng triệu hạt phấn li ti siêu nhỏ siêu mịn bám đều và mịn trên bề mặt da sẽ giúp lớp trang điểm mịn màng,nhẹ nhàng, tươi sáng, đồng thời giúp che phủ các khuyết điểm trên da hiệu quả. ', 2860000,30,'L013','N012','SP46.JPG','46_1.jpg;46_2.jpg;46_3.jpg;46_4.jpg'),
	('SP047',N'Bake Terracotta Powder',N'Phấn Phủ Dạng Nén 2 Màu Flormar 023 Dual Gold Bake Terracotta Powder là sản phẩm thuộc thương hiệu flormar đến từ Ý. Sản phẩm giúp tôn lên các màu sắc đã được dùng trước đó trên da mà không làm thay đổi màu sắc của chúng.', 2460000,70,'L013','N019','SP47.JPG','47_1.jpg;47_2.jpg;47_3.jpg;47_4.jpg'),
	('SP048',N'Speed White CC Powder Pact SPF40 PA+++',N'Đối với công cuộc làm đẹp hằng ngày của chị em, Phấn phủ chắc chắn sẽ một trong những món không thể thiếu để chúng ta có thể tự tin "sống ảo". Phấn Phủ Sáng Da SPF40/PA+++ từ thương hiệu Cathy Doll với chất phấn mỏng mịn, nhẹ nhàng tiệp vào da mà không bị giả cùng độ kiểm soát dầu tốt và lâu trôi suốt cả ngày dài chắc chắn sẽ là "hot item" mà các nàng không thể bỏ qua', 3770000,80,'L013','N011','SP48.JPG','48_1.jpg;48_2.jpg;48_3.jpg;48_4.jpg'),
	('SP049',N'Clear Smooth All In One Light UV + Lightening Oil Control Pressed Powder',N'Phấn Phủ Mịn Da Chống Nhờn Maybelline Clear Smooth All In One Light UV + Lightening Oil Control Pressed Powder SPF20/PA+++ đến từ thương hiệu mỹ phẩm trang điểm Maybelline của Mỹ là dòng sản phẩm phấn phủ dành cho da dầu, có khả năng hút bã nhờn hiệu quả cùng kết cấu hạt phấn mịn, giúp mang lại làn da mịn màng, không bóng nhờn suốt 8 giờ. Bảng màu bao gồm 3 tông màu phù hợp với làn da châu Á', 3460000,20,'L013','N010','SP49.JPG','49_1.jpg;49_2.jpg;49_3.jpg;49_4.jpg'),
---------------------------------LOẠI 5: PHẤN NƯỚC-----------------------------------
	('SP050',N'Baby Skin Cushion + Baby Skin Powder',N'Sau khi đã dặm cushion lên da, các bạn nên dùng một miếng mút khác và dặm nhẹ lên da để lượng dầu dư thấm vào miếng mút. Cách này sẽ khiến lớp nền trên da lì hơn giảm thiểu được khả năng trôi cushion.', 2330000,20,'L014','N012','SP50.jfif','51_1.jpg;51_2.jpg;51_3.jpg;51_4.jpg'),
	('SP051',N'Baby Skin Cushion + Baby Skin Powder',N'Dùng bông phấn đi kèm hoặc cọ trang điểm để lấy phấn, sau đó dặm nhẹ nhàng lên da, tập trung vào những vùng da nhiều dầu nhờn như vùng chữ T và những vùng có khuyết điểm, lỗ chân lông to', 2350000,40,'L014','N013','SP51.jfif','52_1.jpg;52_2.jpg;52_3.jpg;52_4.jpg'),
	('SP052',N'Professional Magic Cover Cushion #21 Pure Beige SPF 50+/ PA+++',N'Phấn Nước Che Phủ Cao Chouchou Professional Magic Cover Cushion SPF 50+/ PA+++ 15g từ thương hiệu ChouChou của Hàn Quốc là sản phẩm kem nền 3 trong 1 với khả năng che phủ tốt hầu hết các khuyết điểm trên da đồng thời dưỡng ẩm cho da không khô mốc hay đổ dầu. Kèm theo đó là khả năng chống nắng hoàn hảo với chỉ số SPF 50+/ PA+++ là điểm cộng cho sản phẩm tiện lợi, tiết kiệm thời gian cho chị em phụ nữ', 2560000,20,'L014','N014','SP52.jfif','53_1.jpg;53_2.jpg;53_3.jpg;53_4.jpg'),
	('SP053',N'M Magic Cushion (New Edition 2019)',N'Magic Cushion đến từ thương hiệu mỹ phẩm MISSHA nổi tiếng Hàn Quốc, với công thức chứa các hạt sắc tố màu siêu nhỏ có khả năng che phủ tốt các khuyết điểm trên da, cùng với độ bám màu tốt & bền màu lâu trôi, mang đến lớp nền tươi sáng cho bạn gái, kết hợp chỉ số chống nắng SPF50+ PA+++ và khả năng kiềm dầu tuyệt vời mà bạn không nên bỏ qua', 9470000,80,'L014','N012','SP53.jfif','54_1.jpg;54_2.jpg;54_3.jpg;54_4.jpg'),
	('SP054',N'Matte Addict Cushion',N'Phấn Nước Đơn LEMONADE Matte Addict Cushion SPF50+ PA+++ là dòng sản phẩm thuộc thương hiệu mỹ phẩm trang điểm LEMONADE có xuất xứ từ Việt Nam, do “phù thủy makeup” Quách Ánh sáng lập. Đây là sản phẩm được phát triển từ dòng Phấn Nước Matte Addict Dual Cushion đã ra mắt trước đó, với thiết kế đơn KHÔNG kèm theo lõi Face Filler (kem lót), thích hợp cho những bạn chỉ có nhu cầu sử dụng riêng Cushion.', 9370000,90,'L014','N016','SP54.jfif','55_1.jpg;55_2.jpg;55_3.jpg;55_4.jpg'),
	('SP055',N'Baby Skin Cushion SPF 50+ PA+++ (New 2021)',N'Phấn Nước M.O.I Baby Skin Cushion SPF 50+ PA+++ là phiên bản nâng cấp hoàn hảo từ dòng phấn nước 5M Baby Skin Cushion nổi tiếng từ thương hiệu M.O.I Cosmetics, với diện mạo mới hơn, chất lượng dưỡng da đỉnh hơn với giá bán không thể nào hợp lý hơn. Sản phẩm giúp tạo lớp màng bảo vệ mịn mướt, nhẹ nhàng ôm lấy làn da trong những ngày nắng nóng, đồng thời đem đến một làn da trong veo, tự nhiên tựa như làn da em bé', 3460000,60,'L014','N018','SP55.jfif','56_1.jpg;56_2.jpg;56_3.jpg;56_4.jpg'),
	('SP056',N'Veil Fit Cushion SPF50+ PA+++',N'Bộ Phấn Nước Mịn Lì Mờ Khuyết Điểm Essance SPF50+ PA+++ Veil Fit Cushion 15g là sản phẩm đến từ thương hiệu Essance Hàn Quốc. Đây là dòng sản phẩm giới hạn được hãng kết hợp với Jun Phạm cho ra mắt cùng thiết kế vỏ hồng ngọt ngào đẹp mắt', 2860000,30,'L014','N012','SP56.jfif','57_1.jpg;57_2.jpg;57_3.jpg;57_4.jpg'),
	('SP057',N'Gen Matte Cushion Foundation',N'Phấn Nước Dạng Thỏi SILKYGIRL Gen Matte Cushion Foundation SPF25. Dù bạn là cô nàng khó tính trong việc lựa chọn kem nền ra sao thì “tân binh” này chắc chắn cũng sẽ làm bạn “đổ gục” trước độ mỏng mịn, tiệp màu và lâu trôi của em nó', 2460000,70,'L014','N019','SP57.jfif','58_1.jpg;58_2.jpg;58_3.jpg;58_4.jpg'),
	('SP058',N'Magic Cover Cushion SPF50++ #22 Natural',N'Phấn Nước Trang Điểm Vacosi Magic Cover Cushion SPF50++ 13g là dòng phấn nước đến từ thương hiệu mỹ phẩm Vacosi của Hàn Quốc, với công nghệ Water Blend và bông mút công nghệ mới Dimension & Light đem lại độ che phủ mỏng nhẹ, lớp nền nhẹ như nước, tan ngay và tệp vào da tạo lớp nền mượt mà, căng bóng khỏe', 3770000,80,'L014','N011','SP58.jfif','59_1.jpg;59_2.jpg;59_3.jpg;59_4.jpg'),
	('SP059',N'Magic BB Cushion',N'Phấn nước Cushion đang là một trong những item không thể thiếu trong túi đồ trang điểm của con gái chúng ta. Ngoài ưu điểm dễ sử dụng, tiện lợi, nhanh gọn, phấn nước cushion còn là "chuyên gia" tạo lớp nền mịn đẹp tự nhiên, hoàn hảo. Phấn Nước Trang Điểm SILKYGIRL Magic BB Cushion SPF50/PA+++ giàu nước khoáng giúp cấp ẩm cho làn da thoáng mịn, rạng rỡ suốt 12h đồng đồ và bảo vệ da khỏi tác hại của tia UV nữa đấy nhé', 3460000,20,'L014','N010','SP59.jfif','50_1.jpg;50_2.jpg;50_3.jpg;50_4.jpg'),
---------------------------------LOẠI 6: TẠO KHỐI ---------------------------------
	('SP060',N'Sweet Like Chocolate Bronzer',N'Hộp phấn tạo khối dạng mini tiện dụng bỏ túi và mang theo bất cứ đâu, không chỉ vậy với kích thước phiên bản mini giúp những nàng ít trang điểm cũng có thể yên tâm sở hữu cho mình một sản phẩm tạo khối dễ dàng', 2330000,20,'L015','N012','SP60.jfif','60_1.jpg;60_2.jpg;60_3.jpg;60_4.jpg'),
	('SP061',N'Photosharp Contour & Highlighter',N'Quả không thể phủ nhận xu hướng tạo khối đang thịnh hành trong cộng đồng makeup, chúng rất hữu ích trong việc định hình, làm khuôn mặt trở nên thon gọn, thanh thoát hơn mà không cần dùng đến dao kéo. Bút Tạo Khối Photosharp Contour & Highlighter đến từ thương hiệu SILKYGIRL với thiết kế 2 đầu tiện dụng gồm 1 đầu giúp tạo khối, đầu còn lại làm highlight nhằm bắt sáng khuôn mặt trở nên rạng rỡ, tỏa sáng hơn.', 2350000,40,'L015','N013','SP61.jfif','61_1.jpg;61_2.jpg;61_3.jpg;61_4.jpg'),
	('SP062',N'Artclass By Rodin Shading - 01 Classic',N'Phấn Tạo Khối Too Cool For School Artclass by Rodin Shading là sản phẩm tạo khối bán chạy nhất của thương hiệu Too Cool For School, với 3 tông màu kết hợp trong 1 hộp phấn nhỏ gọn kèm gương soi tiện dụng, giúp tạo điểm nhấn, góc cạnh đặc biệt nhằm tôn lên đường nét thanh thoát tự nhiên cho gương mặt', 2560000,20,'L015','N014','SP62.jfif','62_1.jpg;62_2.jpg;62_3.jpg;62_4.jpg'),
	('SP063',N'Contour Highlight & Shading',N'Bảng Tạo Khối Chuyên Nghiệp Vacosi 12HS 12 Ô Contour Highlight & Shading là sản phẩm đến từ thương hiệu Vacosi của Hàn Quốc. Sở hữu sản phẩm bạn sẽ không cần phải mua thêm bất cứ sản phẩm bắt sáng hay tạo khối nào khác. Sản phẩm thích hợp với mọi phong cách trang điểm khác nhau', 9470000,80,'L015','N012','SP63.jfif','63_1.jpg;63_2.jpg;63_3.jpg;63_4.jpg'),
	('SP064',N'AC On Tour Powder Contouring & Highlighting Palette - Light',N'Bảng Tạo Khối & Bắt Sáng 6 Ô Australis Light AC On Tour Powder Contouring & Highlighting Palette đã đạt giải thưởng Best In beauty Award 2017 – Sản phẩm làm đẹp tốt nhất năm 2017', 9370000,90,'L015','N016','SP64.jfif','64_1.jpg;64_2.jpg;64_3.jpg;64_4.jpg'),
	('SP065',N'Fresh & Flawless Concealer #Natural',N'Che Khuyết Điểm Và Tạo Khối Australis Fresh & Flawless Concealer 7.5ml là dòng che khuyết điểm đến từ thương hiệu mỹ phẩm Australis của Úc, với thành phần thuần thực vật chứa Vitamin E, C cải thiện độ ẩm và ngăn ngừa lão hóa cho làn da mịn màng. Sản phẩm với chất kem mỏng mịn với công dụng 2 trong 1 giúp che khuyết điểm toàn diện, và tạo khối trông gương mặt góc cạnh và thu hút hơn.', 3460000,60,'L015','N018','SP65.jfif','65_1.jpg;65_2.jpg;65_3.jpg;65_4.jpg'),
	('SP066',N'Mineralize Skinfinish Natural (Date 04/2022)',N'Phấn Tạo Khối MAC Mineralize Skinfinish Natural đến từ thương hiệu mỹ phẩm trang điểm chuyên nghiệp nổi tiếng M·A·C, là dạng phấn bột nén có pha trộn một chút ánh ngọc trai nhẹ nhàng, cho bạn lớp trang điểm đẹp tự nhiên, có thể sử dụng để tạo khối cho cả mặt và cơ thể, hoặc dùng như phấn phủ cố định lớp trang điểm, có thể dặm lại nhiều lần trong ngày', 2860000,30,'L015','N012','SP66.jfif','66_1.jpg;66_2.jpg;66_3.jpg;66_4.jpg'),
	('SP067',N'Fresh & Flawless Concealer #Beige',N'Che Khuyết Điểm Và Tạo Khối Australis Fresh & Flawless Concealer 7.5ml là dòng che khuyết điểm đến từ thương hiệu mỹ phẩm Australis của Úc, với thành phần thuần thực vật chứa Vitamin E, C cải thiện độ ẩm và ngăn ngừa lão hóa cho làn da mịn màng. Sản phẩm với chất kem mỏng mịn với công dụng 2 trong 1 giúp che khuyết điểm toàn diện, và tạo khối trông gương mặt góc cạnh và thu hút hơn', 2460000,70,'L015','N019','SP67.jfif','67_1.jpg;67_2.jpg;67_3.jpg;67_4.jpg'),
	('SP068',N'Mineralize Skinfinish Natural (Date 08/2022',N'Phấn Tạo Khối MAC Mineralize Skinfinish Natural đến từ thương hiệu mỹ phẩm trang điểm chuyên nghiệp nổi tiếng M·A·C, là dạng phấn bột nén có pha trộn một chút ánh ngọc trai nhẹ nhàng, cho bạn lớp trang điểm đẹp tự nhiên, có thể sử dụng để tạo khối cho cả mặt và cơ thể, hoặc dùng như phấn phủ cố định lớp trang điểm, có thể dặm lại nhiều lần trong ngày', 3770000,80,'L015','N011','SP68.jfif','68_1.jpg;68_2.jpg;68_3.jpg;68_4.jpg'),
	('SP069',N'Artclass By Rodin Highlighter',N'Phấn Bắt Sáng Too Cool For School Artclass By Rodin Highlighter là sản phẩm highlighter đến từ thương hiệu Too Cool For School của Hàn Quốc, được thiết kế ở dạng phấn nén, bao gồm 3 ô màu chứa các hạt nhũ cực nhuyễn mịn, khi lên da bắt sáng cực tốt, tạo hiệu ứng gương mặt rạng rỡ và nổi bật hơn bao giờ hết', 3460000,20,'L015','N010','SP69.jfif','69_1.jpg;69_2.jpg;69_3.jpg;69_4.jpg'),
----------------------------------LOẠI 7: CHE KĐ  -----------------------------------
    ('SP070',N'Fix It Liquid Concealer',N'Kem Che Khuyết Điểm Silkygirl Fix It Liquid Concealer 2ml là sản phẩm che khuyết điểm đến từ thương hiệu mỹ phẩm Silkygirl của Malaysia, kết cấu dạng lỏng dễ dàng che phủ mọi khuyết điểm từ nhẹ đến nặng như: thâm mụn, tàn nhang, đốm nâu và quầng thâm mắt, đem lại cho bạn một lớp nền hoàn hảo và tự nhiên', 2330000,20,'L016','N012','SP70.jfif','70_1.jpg;70_2.jpg;70_3.jpg;70_4.jpg'),
	('SP071',N'True Match The One Concealer',N'Che khuyết điểm là công đoạn không thể thiếu trong quy trình makeup, đặc biệt là đối với các cô nàng làn da có nhiều khuyết điểm và cú đêm chính hiệu. Concealer ngay chốc lát sẽ khiến gương mặt bạn trở nên tươi sáng, đầy sức sống và không tì vết! Đến với Kem Che Khuyết ĐiểmTrue Match The One Concealer của thương hiệu đình đám LOréal Paris sẽ giúp hiệu chỉnh tông màu da, che đi mọi khuyết điểm đồng thời giấu đi sự mệt mỏi, kém sắc trên làn da bạn', 2350000,40,'L016','N013','SP71.jfif','71_1.jpg;71_2.jpg;71_3.jpg;71_4.jpg'),
	('SP072',N'Fit Me Concealer',N'Maybelline New York là công ty mỹ phẩm hàng đầu tại Mỹ. Khởi nguồn từ việc bán mascara qua thư điện tử, mascara Maybelline nhanh chóng trở thành món đồ không thể thiếu được của các cô gái. Ngày nay, mascara Maybelline là mascara được yêu thích của nước Mỹ và được sự tin tưởng của các chuyên gia trang điểm hàng đầu thế giới. Không chỉ dừng lại ở đấy, Maybelline còn mở rộng cung cấp bộ sưu tập trang điểm về toàn phương diện. Bạn sẽ luôn tìm thấy mọi thứ tốt nhất t', 2560000,20,'L016','N014','SP72.jfif','72_1.jpg;72_2.jpg;72_3.jpg;72_4.jpg'),
	('SP073',N'Concealer & Corrector 4 In 1',N'Một trong những bước quan trọng để có được một lớp trang điểm hoàn hảo, mịn màng không tì vết chính là sử dụng kem che khuyết điểm. Bởi vì kem nền không thể che phủ được toàn bộ các khuyết điểm trên gương mặt bạn như quầng thâm, nốt mụn sưng đỏ, vết thâm, vết nám… và dễ khiến nền bị dày, cộm, bí da khó chịu nếu như bạn dùng lượng quá nhiều. Do đó, các sản phẩm che khuyết điểm ra đời để thực hiện nhiệm vụ “phù phép” các khuyết điểm nói trên “biến mất” mà vẫn giữ cho lớp nền được mỏng mịn, tự nhiên nhất có thể.', 9470000,80,'L016','N012','SP73.jfif','73_1.jpg;73_2.jpg;73_3.jpg;73_4.jpg'),
	('SP074',N'Conceal & Correct Palette',N'Được đánh giá là bảng màu đáng được mong đợi nhất trong bộ sưu tập Pro Palette năm 2019, VACOSI PRO STUDIO CONCEAL & CORRECT PALETTE – 20CC đến từ thương hiệu Vacosi là bảng màu duy nhất trên thị trường có đủ 3 chức năng: conceal (che khuyết điểm), correct (chỉnh màu) và shading (tạo khối), chắc chắn sẽ là item không thể thiếu trong cẩm nang trang điểm của phái đẹp', 9370000,90,'L016','N016','SP74.jfif','74_1.jpg;74_2.jpg;74_3.jpg;74_4.jpg'),
	('SP075',N'Perfect Coverage Liquid Concealer',N'Concealer là những mỹ phẩm có thể giúp bạn che đi những vết đỏ bầm ở da, những đốm mụn, nám, rỗ da hay quầng thâm dưới bọng mắt cực kỳ nhanh chóng, nó còn được sử dụng để giúp cho đường viền mắt, môi thêm sắc nét. Che Khuyết Điểm Dạng Lỏng Perfect Coverage Liquid Concealer – một sản phẩm của Flormar sẽ giúp bạn có được lớp nền hoàn hảo như ý muốn.', 3460000,60,'L016','N018','SP75.jfif','75_1.jpg;75_2.jpg;75_3.jpg;75_4.jpg'),
	('SP076',N'Fresh & Flawless Concealer #Light',N'he Khuyết Điểm Và Tạo Khối Australis Fresh & Flawless Concealer 7.5ml là dòng che khuyết điểm đến từ thương hiệu mỹ phẩm Australis của Úc, với thành phần thuần thực vật chứa Vitamin E, C cải thiện độ ẩm và ngăn ngừa lão hóa cho làn da mịn màng. Sản phẩm với chất kem mỏng mịn với công dụng 2 trong 1 giúp che khuyết điểm toàn diện, và tạo khối trông gương mặt góc cạnh và thu hút hơn.', 2860000,30,'L016','N012','SP76.jfif','76_1.jpg;76_2.jpg;76_3.jpg;76_4.jpg'),
	('SP077',N'nstant Age Rewind Eraser Dark Circles Treatment Concealer',N'Che Khuyết Điểm Maybelline Instant Age Rewind Treatment Concealer chính là “cứu tinh” cho những đôi mắt “gấu trúc” cần che đi quầng thâm mệt mỏi và bọng mắt “xấu xí” khi có thể che phủ những khuyết điểm chỉ trong giây lát và giữ kết quả “tuyệt vời” ấy trong nhiều giờ, để bạn có thể tự tin với đôi mắt tươi sáng và gương mặt đầy vẻ trẻ trung. Nếu bạn đang tìm một phép màu như vậy, Maybelline Instant Age Rewind Treatment Concealer chính là sản phẩm dành cho bạn.', 2460000,70,'L016','N019','SP77.jfif','77_1.jpg;77_2.jpg;77_3.jpg;77_4.jpg'),
	('SP078',N'ProAcne Solution Cover Stick',N'Che Khuyết Điểm Cho Da Mụn Eucerin ProAcne Solution Cover Stick là sản phẩm thuộc thương hiệu Eucerin nổi tiếng đến từ Đức. Sản phẩm giúp “che” đi nhanh chóng các vết mụn, thâm, sẹo,... đồng thời hồi phục, sửa chữa làn da khi sản phẩm được sử dụng', 3770000,80,'L016','N011','SP78.jfif','78_1.jpg;78_2.jpg;78_3.jpg;78_4.jpg'),
	('SP079',N'Eyeshadow Primer',N'vì vùng da này thường xuyên cử động. Kem lót mắt sẽ giúp phấn mắt của bạn “ăn màu” hơn, giúp đôi mắt có chiều sâu và cuốn hút hơn, giữ màu sắc lâu trôi và bền đẹp sau nhiều giờ', 3460000,20,'L016','N010','SP79.jfif','79_1.jpg;79_2.jpg;79_3.jpg;79_4.jpg'),
----------------------------------LOẠI 8: SON DƯỠNG ----------------------------------
	('SP080',N'Lip balm',N'Son Dưỡng Môi Himalaya Herbals với thành phần từ bơ cao cấp, giàu vitamin E giúp cung cấp dưỡng chất, dưỡng ẩm sâu giữ cho môi luôn căng mịn, khỏe mạnh, phòng ngừa nứt nẻ do thời tiết hanh khô đồng thời có thể được sử dụng như một lớp lót trước khi tô son màu để chống khô và bảo vệ môi', 2350000,80,'L017','N018','SP80.jfif','80_1.jpg;80_2.jpg;80_3.jpg;80_4.jpg'),
	('SP081',N'Strawberry Shine Lip Care',N'Son Dưỡng Môi Himalaya Herbals với thành phần từ bơ cao cấp, giàu vitamin E giúp cung cấp dưỡng chất, dưỡng ẩm sâu giữ cho môi luôn căng mịn, khỏe mạnh, phòng ngừa nứt nẻ do thời tiết hanh khô đồng thời có thể được sử dụng như một lớp lót trước khi tô son màu để chống khô và bảo vệ môi', 9300004,26,'L017','N013','SP81.jfif','81_1.jpg;81_2.jpg;81_3.jpg;81_4.jpg'),
	('SP082',N'Repairwear Intensive Lip Treatment (Date 09/2022)',N'Clinique Repairwear Intensive Lip Treatment là cây son dưỡng môi giàu dưỡng chất giúp tạo đường nét môi, mang lại vẻ căng mọng cho đôi môi, đồng thời giúp làn môi thêm mượt mềm, quyến rũ. Hơn nữa, bạn có thể sử dụng sản phẩm này như lớp nền môi giúp son môi lên màu chuẩn, tươi sáng và sắc nét hơn.', 9220000,20,'L017','N017','SP82.jfif','82_1.jpg;82_2.jpg;82_3.jpg;82_4.jpg'),
	('SP083',N'Baobab Banana Lip Balm',N'Nếu không được bảo vệ và cung cấp độ ẩm, tình trạng khô môi lại càng tồi tệ hơn. Vì thế, bí quyết để sở hữu đôi môi căng mọng, mịn màng và hồng hào tự nhiên chính là thường xuyên sử dụng son dưỡng môi hằng ngày đấy. Các nàng đừng quên sở hữu cho mình một thỏi son dưỡng môi xinh xắn và mang theo trong túi xách để thoa mỗi khi cần nhé', 2350000,20,'L017','N011','SP83.jfif','83_1.jpg;83_2.jpg;83_3.jpg;83_4.jpg'),
	('SP084',N'Lip Therapy Original Stick',N'Đôi môi khô của bạn sẽ mềm mịn hẳn nếu sử dụng Vaseline thường xuyên. Với công dụng cung cấp chất dinh dưỡng, mang lại cho bạn làn da mềm mại - Son Dưỡng Môi Dạng Thỏi Vaseline Lip Therapy 4.8g có chức năng vừa là son dưỡng môi, giảm nứt nẻ vừa có thể sử dụng như son lót trang điểm, giúp bảo vệ môi và giúp son lên màu chuẩn hơn', 2350000,60,'L017','N013','SP84.jfif','84_1.jpg;84_2.jpg;84_3.jpg;84_4.jpg'),
	('SP085',N'Labocare Pan + Eno Lips Healbalm',N'Có nhiều nguyên nhân làm đôi môi chúng ta xỉn màu, thâm sạm và nứt nẻ khó chịu, vì vậy việc chăm sóc đôi môi khô nứt trở thành vấn đề khó giải quyết của nhiều chị em phụ nữ. Vậy nên Hasaki.vn xin giới thiệu đến các bạn tuýp son dưỡng làm giảm thâm và làm mềm môi Labocare Pan + Eno Lips Healbalm đến từ Mediheal giúp chăm sóc toàn diện cho đôi môi bạn trở nên hồng hào, mềm mại và căng bóng như cánh hoa hồng mới nở.', 2350000,40,'L017','N014','SP85.jfif','85_1.jpg;85_2.jpg;85_3.jpg;85_4.jpg'),
	('SP086',N'Chocolate Lip balm',N'Da môi của chúng ta là vùng da rất mỏng manh nhạy cảm, lại không có tuyến mồ hôi như da mặt nên cực kì dễ bị mất độ ẩm, gây ra tình trạng môi khô nẻ, bong tróc khó chịu. Nếu không được bảo vệ và cung cấp độ ẩm, tình trạng khô môi lại càng tồi tệ hơn. Vì thế, bí quyết để sở hữu đôi môi căng mọng, mịn màng và hồng hào tự nhiên chính là thường xuyên sử dụng son dưỡng môi hằng ngày đấy. Các nàng đừng quên sở hữu cho mình một thỏi son dưỡng môi xinh xắn và mang theo trong túi xách để thoa mỗi khi cần nhé.', 9320000,70,'L017','N012','SP86.jfif','86_1.jpg;86_2.jpg;86_3.jpg;86_4.jpg'),
	('SP087',N'Lip Therapy Cocoa Butter Stick',N'Đôi môi khô của bạn sẽ mềm mịn hẳn nếu sử dụng Vaseline thường xuyên. Với công dụng cung cấp chất dinh dưỡng, mang lại cho bạn làn da mềm mại - Son Dưỡng Môi Dạng Thỏi Vaseline Lip Therapy 4.8g có chức năng vừa là son dưỡng môi, giảm nứt nẻ vừa có thể sử dụng như son lót trang điểm, giúp bảo vệ môi và giúp son lên màu chuẩn hơn', 2350000,70,'L017','N018','SP87.jfif','87_1.jpg;87_2.jpg;87_3.jpg;87_4.jpg'),
	('SP088',N'Dewy Lip Balm',N'Chỉ với một lớp son môi mỏng nhẹ sẽ khiến gương mặt bạn trở nên rạng ngời, sáng bừng sức sống. Sau đây Hasaki xin giới thiệu đến bạn Son Dưỡng Có Màu B.O.M Dewy Lip Balm với thành phần chính là chiết xuất từ bơ hạt mỡ sẽ giúp chăm sóc cho làn môi của bạn thêm phần căng mọng, mịn màng trông thấy. Cùng tông màu hồng ngọt ngào, dịu dàng sẽ giúp biến hóa khuôn mặt bạn trở nên tươi tắn, xinh yêu hơn h', 2720000,30,'L017','N010','SP88.jfif','88_1.jpg;88_2.jpg;88_3.jpg;88_4.jpg'),
	('SP089',N'Original Care Caring Lip Balm',N'Son Dưỡng Môi Nivea Caring Lip Balm là dòng sản phẩm chăm sóc da môi đến từ thương hiệu mỹ phẩm Nivea danh tiếng xuất xứ từ Đức, có công thức không chứa chì an toàn cho làn da môi nhạy cảm, giúp cung cấp độ ẩm chuyên sâu giúp da môi luôn mềm mượt và mịn màng', 7540000,20,'L017','N019','SP89.jfif','89_1.jpg;89_2.jpg;89_3.jpg;89_4.jpg'),
----------------------------------LOẠI 9: SON LÌ  ---------------------------------
	('SP090',N'Color Sensational Inti-Matte Nudes Lipstick',N'Maybelline Color Sensational Inti-Matte Nudes Lipstick là bộ sưu tập son Nude mới nhất cùng 10 màu son nude thời thượng, phù hợp với mọi tông da của các cô nàng Châu Á. Son lì Maybelline xuất hiện đình đám làm khuấy đảo cộng đồng mạng, còn được ví như Nars, hay MAC thần thánh mà giá cả lại vô cùng bình dân. Còn chần chờ gì nữa! Nhanh tay tậu cho mình một em về nhà ngay nhé', 3420000,50,'L018','N018','SP90.jfif','90_1.jpg;90_2.jpg;90_3.jpg;90_4.jpg'),
	('SP091',N'Extreme Matte Lipstick',N'Extreme Matte Lipstick', 2300000,70,'L018','N012','SP91.jfif','91_1.jpg;91_2.jpg;91_3.jpg;91_4.jpg'),
	('SP092',N'Im Matte Lipcolor',N'Son từ lâu đã trở thành một biểu tượng sắc đẹp không thể thiếu đối với phái nữ, son được ví von như chiếc gậy ma thuật giúp phái nữ đẹp lên trong phút chốc. Trong khi cơn sốt son lì chưa có dấu hiệu "hạ nhiệt", để chiều lòng các tín đồ Makeup, SILKYGIRL vừa cho ra mắt bộ sưu tập Son Lì Mượt Môi Im Matte Lipcolor mới, hứa hẹn sẽ đem đến trải nghiệm thật tuyệt với chất son mịn lì cùng các tông màu đầy thời thượng. Còn gì tuyệt hơn khi được thỏa sức nhấn nhá và tự tin thể hiện phong cách ', 2350000,90,'L018','N015','SP92.jfif','92_1.jpg;92_2.jpg;92_3.jpg;92_4.jpg'),
	('SP093',N'Im Matte Lipcolor',N'Son từ lâu đã trở thành một biểu tượng sắc đẹp không thể thiếu đối với phái nữ, son được ví von như chiếc gậy ma thuật giúp phái nữ đẹp lên trong phút chốc. Trong khi cơn sốt son lì chưa có dấu hiệu "hạ nhiệt", để chiều lòng các tín đồ Makeup, SILKYGIRL vừa cho ra mắt bộ sưu tập Son Lì Mượt Môi Im Matte Lipcolor mới', 6540000,20,'L018','N011','SP93.jfif','93_1.jpg;93_2.jpg;93_3.jpg;93_4.jpg'),
	('SP094',N'OMG! Powder Matte',N'Son Lì Siêu Mịn SILKYGIRL OMG! Powder Matte (New Color) 3.5g là dòng son lì đến từ thương hiệu mỹ phẩm SILKYGIRL của Malaysia, với hiệu ứng "Power-light" độc đáo, thỏi son dễ dàng lướt nhẹ trên môi giúp lên màu chuẩn lì hơn bao giờ hết, mà không gây khô môi hay lộ rãnh môi. Đặc biệt hơn hết, với thiết kế cực chất, phần vỏ ngoài có nút bấm mở chắc chắn và gương soi mini.', 3760000,80,'L018','N017','SP94.jfif','94_1.jpg;94_2.jpg;94_3.jpg;94_4.jpg'),
	('SP095',N'Matte Fever Lipcolor Balm',N'Son môi luôn là món phụ kiện không thể thiếu của các chị em phụ nữ, từ những cô nàng say mê làm đẹp đến những cô nàng thích đơn giản mộc mạc nhất. Cũng vì lí do đó, các hãng mỹ phẩm ngày nay liên tục tung ra muôn vàn dòng son môi mới nhưng không chỉ chú trọng nhiều ở bảng màu sắc đa dạng, hợp thời mà còn phát triển phong phú hơn về kiểu dáng.', 3730000,30,'L018','N013','SP95.png','95_1.jpg;95_2.jpg;95_3.jpg;95_4.jpg'),
	('SP096',N'Color Matte Lipstick',N'Trước xu thế son lì đang đổ bộ hiện nay, VACOSI đã cho ra mắt dòng Son Lì Mịn Môi Vacosi Color Matte Lipstick với màu sắc đầy mê hoặc, cuốn hút. Với chất son cải tiến mới không gây khô môi, Color Matte Lipstick nhẹ nhàng lướt nhẹ trên môi tựa như nhung & giữ môi mềm mượt suốt nhiều giờ liền. Em ấy còn hứa hẹn sẽ là thỏi son yêu thích của các tín đồ làm đẹp trong thời khắc thu-đông 2018 nữa đấy nhé!', 7560000,70,'L018','N016','SP96.jfif','96_1.jpg;96_2.jpg;96_3.jpg;96_4.jpg'),
	('SP097',N'Extreme Matte Lipstick',N'Nếu bạn đang tìm kiếm một thỏi son chuẩn lì, lên màu chuẩn, nhẹ môi và hoàn toàn không gây khô môi thì nhất định bạn không thể bỏ qua dòng son siêu lì flormar Extreme Matte Lipstick đâu đấy nhé! Son lì Flormar Extreme Matte Lipstick là dòng son cực lì, màu sắc son vô cùng đa dạng dễ dàng lựa chọn cho nhiều phong cách và thích hợp với mọi cô nàng đam mê son lì', 2570000,30,'L018','N019','SP97.jfif','97_1.jpg;97_2.jpg;97_3.jpg;97_4.jpg'),
	('SP098',N'Hydro Shine Lips Matte',N'Là bản hòa phối ấn tượng của màu sắc và thị giác, tông son đỏ vượt lên trên mọi tông màu khác và trở thành nữ hoàng tô điểm cho phái đẹp trở nên lôi cuốn và quyến rũ. Nếu là tín đồ của tông son quyền lực này, cây Son Lì Mịn Môi Mira Hydro Shine Lips Matte chính là món đồ mỹ phẩm bạn không thể bỏ qua. Son môi dạng lì với chất son bổ sung dưỡng chất giúp đôi môi thêm tươi tắn và mềm mại', 8430000,80,'L018','N014','SP98.jfif','98_1.jpg;98_2.jpg;98_3.jpg;98_4.jpg'),
	('SP099',N'GRLBOSS Satin Lipstick',N'Son Lì Dưỡng Môi Australis GRLBOSS Satin Lipstick từ thương hiệu Australis của Úc là dòng son lì đặc biệt với độ dưỡng ẩm cao cùng chất son mướt mịn, che phủ cực tốt khuyết điểm trên môi và giữ môi mềm mượt, căng mọng mang đến vẻ ngoài quyến rũ, gợi cảm. Son không chỉ lên màu chuẩn mà còn lâu trôi, bền màu suốt ngày dài chắc chắn sẽ là dòng son bạn muốn trải nghiệm nhất', 9750000,20,'L018','N018','SP99.jfif','99_1.jpg;99_2.jpg;99_3.jpg;99_4.jpg'),
----------------------------------LOẠI 10: SON BÓNG ---------------------------------
	('SP100',N'Stay True Lipgloss',N'Son Bóng Pretty By Flormar Stay True Lipgloss là sản phẩm trang điểm môi đến từ thương hiệu Pretty By Flormar của Ý. Son bóng với thành phần Polymer kết hợp với bơ hạt mỡ cũng nhiều thành phần dưỡng chất khác với kết cấu chất son mềm mượt và nhẹ giúp tạo hiệu ứng cực sáng bóng, không dầu, không dính rít tạo cho làn môi hiệu ứng căng mọng và quyến rũ', 7550000,30,'L019','N013','SP100.jfif','100_1.jpg;100_2.jpg;100_3.jpg;100_4.jpg'),
	('SP101',N'Get Sweat Matte Tint & Lip Coat',N'Get Sweat Matte Tint & Lip Coat sẽ là món quà tặng đặc biệt thích hợp cho những cô nàng năng động, đam mê thể thao hoặc thường xuyên ra ngoài giao lưu gặp gỡ với bạn bè, cần một thỏi son bền màu lâu trôi suốt cả ngày dài hoạt động', 5670000,80,'L019','N016','SP101.png','101_1.jpg;101_2.jpg;101_3.jpg;101_4.jpg'),
	('SP102',N'Patent Paint Lip Lacquer (Date 07/2022)',N'Son Kem Bóng MAC Patent Paint Lip Lacquer 3.8g là dòng son kem bóng trang điểm môi đến từ thương hiệu mỹ phẩm cao cấp MAC của Mỹ, công thức dạng son kem cùng hiệu ứng sáng bóng vinyl đặc biệt, có khả năng cung cấp cho đôi môi độ ẩm suốt cả ngày với khả năng lên màu chuẩn và độ bám màu nhiều tiếng đồng hồ', 3470000,20,'L019','N012','SP102.jfif','102_1.jpg;102_2.jpg;102_3.jpg;102_4.jpg'),
	('SP103',N'Versicolour Varnish Cream Lip Stain #111 Crushing It (Date 11/2021)',N'Son Kem Bóng Mịn Môi MAC Versicolour Cream Lip Stain là sản phẩm đến từ thương hiệu MAC đình đám nổi tiếng của Mỹ, sản phẩm với công thức giữ ẩm vượt trội kết hợp cùng sự pha trộn độc đáo giữa các loại dầu khoáng, giúp bảo vệ môi mềm mại và tạo hiệu ứng sáng bóng cho đôi môi', 2350000,90,'L019','N018','SP103.jfif','103_1.jpg;103_2.jpg;103_3.jpg;103_4.jpg'),
	('SP104',N'Colorable Draw Tint',N'Sau một thời gian “im hơi lặng tiếng” trên thị trường, nhà It’s Skin đã vừa tung ra một dòng son “mới keng xà beng” đó chính là Colorable Draw Tint. Lấy cảm hứng từ mùa tựu trường Back to School, It’s Skin đã tạo nên dòng son với thiết kế thật sự độc đáo – những thỏi son kem hình bút chì đầy màu sắc, tạo nên nguồn cảm hứng vô tận cho giới trẻ, đặc biệt là những bạn học sinh sinh viên tràn đầy năng động và nhiệt huyết! Sản phẩm có chất son kem lì “chuẩn trend” ', 7540000,40,'L019','N012','SP104.jfif','104_1.jfif;104_2.jpg;104_3.jpg;104_4.jpg'),
	('SP105',N'Diamond Shine Light Pink',N'Nếu bạn là một cô gái yêu thích những thỏi son có màu sắc tươi sáng, lâu phai nhưng sợ dùng son lì sẽ gây khô môi thì Son Nhũ Trang Điểm Dưỡng Tối Ưu Lip On Lip Diamond Shine sẽ là một gợi ý không tồi cho bạn. Thỏi son thuộc dòng son có nhũ, độ dưỡng cao nên son rất ẩm mượt, khi apply lên môi giúp tạo hiệu môi mọng, mềm, tràn đầy sức sống', 2340000,80,'L019','N018','SP105.jfif','105_1.jpg;105_2.jpg;105_3.jpg;105_4.jpg'),
	('SP106',N'Rouge Unlimited Amplified Matte RD195',N'Son Lì Shu Uemura Rouge Unlimited Matte 3g từ thương hiệu Shu Uemura của Nhật Bản là dòng son trang điểm môi cao cấp với sự kết hợp hoàn mỹ giữa chất son lì thượng hạng và kết cấu mịn nhẹ như nhung, cho sắc son được bền màu mà vẫn duy trì cảm giác thoải mái, nhẹ nhàng suốt ngày dài. Đặc biệt, công nghệ khuếch tán hạt sắc tố màu mang lại màu sắc thuần túy, cho đôi môi bùng nổ màu sắc đầy cá tính khiến các nàng không khỏi ngất ngây', 7650000,30,'L019','N014','SP106.jfif','106_1.jpg;106_2.jpg;106_3.jpg;106_4.jpg'),
	('SP107',N'OMG! Powder Matte',N'Son Lì Siêu Mịn SILKYGIRL OMG! Powder Matte (New Color) 3.5g là dòng son lì đến từ thương hiệu mỹ phẩm SILKYGIRL của Malaysia, với hiệu ứng "Power-light" độc đáo, thỏi son dễ dàng lướt nhẹ trên môi giúp lên màu chuẩn lì hơn bao giờ hết, mà không gây khô môi hay lộ rãnh môi. Đặc biệt hơn hết, với thiết kế cực chất, phần vỏ ngoài có nút bấm mở chắc chắn và gương soi mini', 2780000,30,'L019','N018','SP107.jfif','107_1.jpg;107_2.jpg;107_3.jpg;107_4.jpg'),
	('SP108',N'Moisture Rich Lipcolor',N'on môi được xem là vật dụng không thiếu thiếu đối với các cô nàng phái đẹp chúng ta. Chỉ cần một chút son lớt nhẹ trên bờ môi cũng đủ khiến cả gương mặt như sáng bừng, tươi tắn đến không ngờ. Son Màu Giàu Dưỡng Chất SILKYGIRL Moisture Rich Lipcolor chứa thành phần dưỡng ẩm, giúp bề mặt son mềm mượt, dịu nhẹ, tạo độ bóng mịn khi thoa, cho bạn làn môi căng mọng, tăng vẻ gợi cảm và quyến rũ.', 2860000,50,'L019','N012','SP108.jfif','108_1.jpg;108_2.jpg;108_3.jpg;108_4.jpg'),
	('SP109',N'Stay All Day Lip Stain - Nama Slay',N'Bạn chán ghét việc phải chờ đợi son khô sau khi thoa, son thường xuyên dính vào thành cốc khi uống nước, son nhanh trôi màu sau khi ăn khiến bạn phải mất công thoa đi thoa lại nhiều lần trong ngày, hay nhiều loại son lì bạn dùng gây cảm giác nặng môi khó chịu… Hãy thử trải nghiệm dòng sản phẩm Son Kem Siêu Lì Nhẹ Môi Australis Slay All Day Lip Stain sẽ giúp mang lại cho bạn một đôi môi đẹp rạng rỡ hoàn hảo mà vẫn nhẹ tênh, mịn lì, cảm giác “có mà như không', 4660000,40,'L019','N019','SP109.jfif','109_1.jpg;109_2.jpg;109_3.jpg;109_4.jpg')


GO
SET DATEFORMAT DMY
INSERT INTO NHANVIEN
VALUES('leluuhoangnhan',N'LÊ LƯU HOÀNG NHÂN','01/03/2001',N'NAM',N'QUAN TRI','0938237485','LELUUHOANGNHAN@GMAIL.COM',N'HỒ CHÍ MINH','leluuhoangnhan','leluuhoangnhan.jpg','123')



SELECT * FROM LOAI
SELECT * FROM NHASANXUAT
SELECT * FROM SANPHAM
SELECT * FROM KHACHHANG
SELECT * FROM DONHANG
SELECT * FROM NHANVIEN




-------------------@BẢN QUYỀN THUỘC LÊ LƯU HOÀNG NHÂN (ĐỒ ÁN CẢ NHÓM CÔNG NGHỆ WEB)---------------------