/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Image;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Types;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author LeLuuHoangNhan
 */
public class ChiTietCDT extends javax.swing.JFrame {
    private Connection conn;
    /**
     * Creates new form ChiTietThue
     */
    public ChiTietCDT() {
        initComponents();
        
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            conn=DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databasename=DB_QLDA;"
                    + "username=sa;password=1321");
            
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        
        txt_maCDT.setEnabled(false);
        txt_tenCDT.setEnabled(false);
        txt_ngayDKKD.setEnabled(false);

        txt_tongSLDA.setEnabled(false);
        
        
        
//        ImageIcon img = new ImageIcon(new ImageIcon("src/img/LeLuuHoangNhan.png").getImage().getScaledInstance(400, 250, Image.SCALE_DEFAULT));
//        lbl_hinhAnh.setText("");
//        lbl_hinhAnh.setIcon(img);
        
    }
    
    public void xuatThongTin(String maCDT)
    {
        if(maCDT.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Erro khong nhan duoc gia tri maCDT!");
        }
        else
        {
            String sql="SELECT DISTINCT MACDT,TENCDT,NGAY_DKKD, IMG FROM CHUDAUTU WHERE MACDT=?";
            try
            {
                PreparedStatement ps=conn.prepareStatement(sql);
                ps.setString(1, maCDT);
                ResultSet rs=ps.executeQuery();
                while(rs.next())
                {
                    txt_maCDT.setText(rs.getString(1));
                    txt_tenCDT.setText(rs.getString(2));
                    txt_ngayDKKD.setText(rs.getDate(3).toString());
                    
                    ImageIcon img = new ImageIcon(new ImageIcon("src/img/" + rs.getString(4)).getImage().getScaledInstance(400, 250, Image.SCALE_DEFAULT));
                    lbl_hinhAnh.setText("");
                    lbl_hinhAnh.setIcon(img);
                }
                rs.close();
                ps.close();
                
                txt_tongSLDA.setText(String.valueOf(goi_Ham_DemSL_DA(maCDT)));
                
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this, "Loi xuat thong tin chi tiet CDT (1)!");
                e.printStackTrace();
            }
        }
        
    }
    
    public int goi_Ham_DemSL_DA(String maCDT)
    {
        int sl=0;
        String sql="{?=CALL HAM_DEM_SL_DUAN_CDT(?)}";
        try{
            PreparedStatement ps=conn.prepareStatement(sql); 
            CallableStatement cs=ps.getConnection().prepareCall(sql);
            cs.registerOutParameter(1, Types.INTEGER);
            cs.setString(2, maCDT);
            cs.execute();
            
            sl=cs.getInt(1);
            cs.close();
            ps.close();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        return sl;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        lbl_hinhAnh = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_quayLai = new javax.swing.JButton();
        txt_maCDT = new javax.swing.JTextField();
        txt_tenCDT = new javax.swing.JTextField();
        txt_ngayDKKD = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_tongSLDA = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_hinhAnh.setText("...");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("THÔNG TIN CHI TIẾT CHỦ ĐẦU TƯ");

        jLabel2.setText("Mã CĐT :");

        jLabel3.setText("Tên CĐT :");

        jLabel4.setText("Ngày DKKD :");

        btn_quayLai.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_quayLai.setText("Quay lại");
        btn_quayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quayLaiActionPerformed(evt);
            }
        });

        jLabel7.setText("Tổng số lượng dự án đã đầu tư:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(34, 34, 34)
                                .addComponent(txt_maCDT))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txt_ngayDKKD, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_tenCDT)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(19, 19, 19))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btn_quayLai)
                                .addGap(152, 152, 152))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txt_tongSLDA, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(42, 42, 42))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbl_hinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lbl_hinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_maCDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txt_tenCDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_ngayDKKD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_tongSLDA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 21, Short.MAX_VALUE)
                .addComponent(btn_quayLai)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_quayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quayLaiActionPerformed
        this.setVisible(false);
        ChuDauTu cdt=new ChuDauTu();
        cdt.setVisible(true);
    }//GEN-LAST:event_btn_quayLaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChiTietCDT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChiTietCDT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChiTietCDT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChiTietCDT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChiTietCDT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_quayLai;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lbl_hinhAnh;
    private javax.swing.JTextField txt_maCDT;
    private javax.swing.JTextField txt_ngayDKKD;
    private javax.swing.JTextField txt_tenCDT;
    private javax.swing.JTextField txt_tongSLDA;
    // End of variables declaration//GEN-END:variables
}
