<?xml version="1.0" encoding="utf-8"?><Database Name="DB_QLSHOPMYPHAM" Class="DB_QLSHOPMYPHAMDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=LELUUHOANGNHAN;Initial Catalog=DB_QLSHOPMYPHAM;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DB_QLSHOPMYPHAMConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DONHANG" Member="DONHANGs">
    <Type Name="DONHANG">
      <Column Name="MADH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MASP_DATMUA" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GIA" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="NGAYDATMUA" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NGAYGIAOHANG" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="MAKH" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="KHACHHANG_DONHANG" Member="KHACHHANG" ThisKey="MAKH" OtherKey="MAKH" Type="KHACHHANG" IsForeignKey="true" />
      <Association Name="SANPHAM_DONHANG" Member="SANPHAM" ThisKey="MASP_DATMUA" OtherKey="MASP" Type="SANPHAM" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KHACHHANG" Member="KHACHHANGs">
    <Type Name="KHACHHANG">
      <Column Name="MAKH" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENKH" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NGAYSINH" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="GIOITINH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DS_MASP_DAMUA" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="LOAIKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="MATAIKHOAN_LOGIN" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IMG_KH" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="MATKHAU" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="KHACHHANG_DONHANG" Member="DONHANGs" ThisKey="MAKH" OtherKey="MAKH" Type="DONHANG" />
    </Type>
  </Table>
  <Table Name="dbo.LOAI" Member="LOAIs">
    <Type Name="LOAI">
      <Column Name="MALOAI" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENLOAI" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NOINHAPKHAU" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Association Name="LOAI_SANPHAM" Member="SANPHAMs" ThisKey="MALOAI" OtherKey="MALOAI" Type="SANPHAM" />
    </Type>
  </Table>
  <Table Name="dbo.NHANVIEN" Member="NHANVIENs">
    <Type Name="NHANVIEN">
      <Column Name="MANV" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENNV" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NGAYSINH" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="GIOITINH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LOAINV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="MATAIKHOAN_LOGIN" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IMG_NV" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="MATKHAU_NV" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.NHASANXUAT" Member="NHASANXUATs">
    <Type Name="NHASANXUAT">
      <Column Name="MANSX" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENNSX" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="THOIGIANTHANHLAP" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="IMG_LOGO" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Association Name="NHASANXUAT_SANPHAM" Member="SANPHAMs" ThisKey="MANSX" OtherKey="MANSX" Type="SANPHAM" />
    </Type>
  </Table>
  <Table Name="dbo.SANPHAM" Member="SANPHAMs">
    <Type Name="SANPHAM">
      <Column Name="MASP" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENSP" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MOTA" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="GIA" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MALOAI" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MANSX" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IMG_SP" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="DS_HINH" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Association Name="SANPHAM_DONHANG" Member="DONHANGs" ThisKey="MASP" OtherKey="MASP_DATMUA" Type="DONHANG" />
      <Association Name="LOAI_SANPHAM" Member="LOAI" ThisKey="MALOAI" OtherKey="MALOAI" Type="LOAI" IsForeignKey="true" />
      <Association Name="NHASANXUAT_SANPHAM" Member="NHASANXUAT" ThisKey="MANSX" OtherKey="MANSX" Type="NHASANXUAT" IsForeignKey="true" />
    </Type>
  </Table>
</Database>